"""Setup notes for each catalog connector: docs URL, MCP publisher, comments.

Merged onto catalog() rows as `docs` / `publisher` / `notes`. Publisher is
`official`, `community`, `aggregator`, `partial`, or `none`. Aggregator means
Zapier / Composio / Pipedream — not a first-party MCP URL we can OAuth to.
"""

from __future__ import annotations

# type, publisher, docs URL, notes
_ROWS: list[tuple[str, str, str, str]] = [
    (
        "360nrs",
        "none",
        "https://apidocs.360nrs.com/",
        "SMS/email/voice API docs. No MCP.",
    ),
    (
        "4dem",
        "none",
        "https://pipedream.com/apps/-4dem",
        "Email marketing API via Pipedream. No MCP.",
    ),
    (
        "abyssale",
        "aggregator",
        "https://composio.dev/toolkits/abyssale",
        "Composio-hosted toolkit.",
    ),
    (
        "acelle_mail",
        "aggregator",
        "https://zapier.com/mcp/acelle-mail",
        "Zapier MCP for self-hosted Acelle Mail.",
    ),
    (
        "activecampaign",
        "official",
        "https://developers.activecampaign.com/page/mcp",
        "Official remote MCP server.",
    ),
    (
        "active_trail",
        "aggregator",
        "https://composio.dev/toolkits/active_trail",
        "Composio toolkit; also on Pipedream.",
    ),
    (
        "acumbamail",
        "community",
        "https://github.com/ever-works/awesome-mcp-servers/blob/master/details/acumbamail-mcp-server.md",
        "Listed in awesome-mcp-servers.",
    ),
    (
        "acymailing",
        "aggregator",
        "https://mcp.pipedream.com/app/acymailing",
        "Pipedream-generated actions.",
    ),
    (
        "add_to_calendar_pro",
        "none",
        "https://add-to-calendar-pro.com/",
        "WP/JS plugin. No MCP.",
    ),
    ("adhook", "none", "", "No public docs surfaced."),
    (
        "adrapid",
        "aggregator",
        "https://mcp.pipedream.com/app/adrapid",
        "Pipedream-hosted.",
    ),
    (
        "adroll",
        "official",
        "https://help.adroll.com/hc/en-us/articles/44128588376077-AdRoll-MCP-Server-Beta",
        "Official MCP beta (2026).",
    ),
    (
        "adtraction",
        "aggregator",
        "https://zapier.com/mcp/adtraction",
        "Affiliate network via Zapier MCP.",
    ),
    (
        "aimtell",
        "none",
        "https://developers.aimtell.com/reference/api-send-push-notification",
        "Push notification REST API. No MCP.",
    ),
    (
        "airship",
        "official",
        "https://www.airship.com/docs/developer/ai-tools/mcp-server/",
        "Official MCP. Also github.com/urbanairship/agent-tools.",
    ),
    (
        "airtable",
        "official",
        "https://support.airtable.com/articles/9897799762-using-the-airtable-mcp-server",
        "Official MCP. Popular alt: github.com/domdomegg/airtable-mcp-server.",
    ),
    (
        "amazon_advertising",
        "official",
        "https://advertising.amazon.com/library/news/amazon-ads-mcp-server-open-beta",
        "Dotobot uses advertising-ai.amazon.com/mcp.",
    ),
    (
        "anthropic",
        "none",
        "https://github.com/modelcontextprotocol/servers",
        "Anthropic authored the MCP spec and reference servers; this is a provider, not a service MCP.",
    ),
    (
        "apexverify",
        "aggregator",
        "https://composio.dev/toolkits/apexverify",
        "Composio-hosted.",
    ),
    (
        "appsflyer",
        "none",
        "https://dev.appsflyer.com/",
        "AppsFlyer API docs. No MCP in the research table.",
    ),
    (
        "arpoone",
        "none",
        "https://docs.arpoone.com/api-reference/",
        "General API reference. No MCP.",
    ),
    (
        "asana",
        "official",
        "https://developers.asana.com/docs/mcp-server",
        "Vendor-hosted remote MCP.",
    ),
    ("asters", "none", "", "Niche/unclear vendor. No public docs."),
    (
        "attentive",
        "none",
        "https://docs.attentivemobile.com/",
        "General API docs. No MCP.",
    ),
    ("autoklose", "none", "https://autoklose.com/", "No MCP found."),
    (
        "automizy",
        "none",
        "https://www.getresponse.com/",
        "Discontinued / absorbed into GetResponse.",
    ),
    (
        "aweber",
        "official",
        "https://docs.aweber.com/integrations/integrations/aweber-mcp-integration-ai-powered-email-marketing-management",
        "Dotobot uses mcp.aweber.com/mcp.",
    ),
    (
        "beamer",
        "aggregator",
        "https://composio.dev/toolkits/beamer",
        "Composio-generated.",
    ),
    (
        "beehiiv",
        "official",
        "https://www.beehiiv.com/features/mcp",
        "Dotobot uses mcp.beehiiv.com/mcp.",
    ),
    (
        "benchmark_email",
        "aggregator",
        "https://composio.dev/toolkits/benchmark_email",
        "Composio; also Zapier/Pipedream.",
    ),
    (
        "bigmailer",
        "aggregator",
        "https://composio.dev/toolkits/bigmailer",
        "Composio; also Pipedream/viaSocket.",
    ),
    (
        "bitly",
        "official",
        "https://dev.bitly.com/bitly-mcp/overview/what-is-mcp",
        "Dotobot uses api-ssl.bitly.com/v4/mcp.",
    ),
    (
        "botconversa",
        "aggregator",
        "https://mcp.pipedream.com/app/botconversa",
        "Pipedream-generated.",
    ),
    (
        "brandfetch",
        "official",
        "https://docs.brandfetch.com/mcp/overview",
        "Dotobot uses mcp.brandfetch.io/mcp.",
    ),
    ("brandmentions", "none", "https://brandmentions.com/", "No MCP found."),
    (
        "braze",
        "official",
        "https://www.braze.com/docs/user_guide/brazeai/mcp_server",
        "Dotobot uses mcp.braze.com/mcp.",
    ),
    (
        "builderall_mailingboss",
        "aggregator",
        "https://viasocket.com/mcp/builderall-mailingboss",
        "Third-party viaSocket connector.",
    ),
    ("buysellads", "none", "https://docs.buysellads.com/", "No MCP found."),
    (
        "calendly",
        "official",
        "https://developer.calendly.com/calendly-mcp-server",
        "Dotobot uses mcp.calendly.com.",
    ),
    (
        "callpage",
        "aggregator",
        "https://composio.dev/toolkits/callpage",
        "Composio-generated.",
    ),
    (
        "callrail",
        "community",
        "https://www.pulsemcp.com/servers/blue-interactive-callrail",
        "Third party; also on Zapier.",
    ),
    (
        "campaign_cleaner",
        "aggregator",
        "https://composio.dev/toolkits/campaign_cleaner",
        "Composio-generated.",
    ),
    (
        "campaign_monitor",
        "community",
        "https://www.stackone.com/connectors/campaignmonitor/mcp/",
        "Also glama.ai/mcp/servers/pauliowest/cmon-mcp.",
    ),
    (
        "campaignhq",
        "none",
        "https://campaignhq.docs.apiary.io/",
        "Official Ruby API client, no MCP.",
    ),
    (
        "campayn",
        "none",
        "https://github.com/nebojsac/Campayn-API",
        "Composio toolkit appears auto-generated only.",
    ),
    ("cardly", "none", "https://api.card.ly/v2/docs", "No genuine dedicated MCP."),
    ("catch_all_verifier", "none", "https://catchallverifier.com/", "No docs found."),
    (
        "chatrace",
        "none",
        "https://chatrace.com/",
        "Only automation listings, no genuine MCP.",
    ),
    (
        "cleverreach",
        "aggregator",
        "https://zapier.com/mcp/cleverreach",
        "Official API: developers.cleverreach.com.",
    ),
    (
        "clevertap",
        "community",
        "https://github.com/ralphcorleone/clevertap-mcp",
        "Also Zapier/Pipedream.",
    ),
    (
        "clickfunnels",
        "official",
        "https://support.myclickfunnels.com/docs/clickfunnels-mcp-server-beta-1",
        "Vendor MCP beta.",
    ),
    (
        "clickup",
        "official",
        "https://developer.clickup.com/docs/connect-an-ai-assistant-to-clickups-mcp-server",
        "Dotobot uses mcp.clickup.com/mcp.",
    ),
    (
        "cloud_convert",
        "aggregator",
        "https://composio.dev/toolkits/cloudconvert/framework/claude-agents-sdk",
        "No standalone official/community repo.",
    ),
    (
        "cometly",
        "official",
        "https://docs.cometly.com/mcp/overview",
        "Vendor MCP.",
    ),
    (
        "constant_contact",
        "community",
        "https://github.com/BusyBee3333/constant-contact-mcp-2026-complete",
        "Also Zapier/Pipedream.",
    ),
    (
        "contentdrips",
        "none",
        "https://developer.contentdrips.com/",
        "No dedicated MCP.",
    ),
    (
        "contentful",
        "official",
        "https://www.contentful.com/developers/docs/tools/mcp-server/",
        "Dotobot uses mcp.contentful.com/mcp.",
    ),
    (
        "convertkit",
        "community",
        "https://github.com/aplaceforallmystuff/mcp-kit",
        "Rebranded Kit; npm: kit-mcp-server.",
    ),
    (
        "copicake",
        "none",
        "https://docs.copicake.com/",
        "Official API/SDKs, no MCP.",
    ),
    (
        "coupontools",
        "none",
        "https://docs.coupontools.com/",
        "REST API, no MCP.",
    ),
    (
        "crowdpower",
        "none",
        "https://docs.crowdpower.io/",
        "REST API, no MCP.",
    ),
    (
        "cufinder",
        "official",
        "https://apidoc.cufinder.io/mcp/introduction",
        "Dotobot uses mcp.cufinder.io/mcp.",
    ),
    (
        "curated",
        "aggregator",
        "https://composio.dev/toolkits/curated",
        "Composio auto-generated.",
    ),
    (
        "customer_io",
        "official",
        "https://docs.customer.io/ai/mcp/get-started/",
        "Dotobot uses mcp.customer.io/mcp.",
    ),
    ("cyberimpact", "none", "https://cyberimpact.com/en/", "No MCP found."),
    (
        "demandbase",
        "official",
        "https://developer.demandbase.com/docs/mcp",
        "Vendor docs.",
    ),
    (
        "demio",
        "aggregator",
        "https://composio.dev/toolkits/demio",
        "Composio toolkit.",
    ),
    (
        "discourse",
        "official",
        "https://github.com/discourse/discourse-mcp",
        "Official. Announced Oct 2025.",
    ),
    (
        "docupost",
        "aggregator",
        "https://composio.dev/toolkits/docupost",
        "Composio toolkit.",
    ),
    (
        "doppler",
        "official",
        "https://github.com/DopplerHQ/mcp-server",
        "Listed MCP is Doppler secrets (docs.doppler.com/docs/mcp). This stub is Doppler marketing automation — verify before connecting.",
    ),
    (
        "dribbble",
        "aggregator",
        "https://zapier.com/mcp/dribbble",
        "Also unofficial Apify scrapers.",
    ),
    (
        "drip",
        "community",
        "https://github.com/GravityKit/drip-mcp-server",
        "drip.com/mcp — verify before calling official.",
    ),
    (
        "dripcel",
        "aggregator",
        "https://docs.composio.dev/toolkits/dripcel",
        "Composio toolkit.",
    ),
    (
        "dropbox",
        "official",
        "https://help.dropbox.com/integrations/connect-dropbox-mcp-server",
        "Dotobot uses mcp.dropbox.com/mcp.",
    ),
    (
        "dropcontact",
        "aggregator",
        "https://zapier.com/mcp/dropcontact",
        "Also composio.dev/toolkits/dropcontact.",
    ),
    (
        "dub",
        "official",
        "https://dub.co/docs/mcp-server",
        "Dotobot uses mcp.dub.sh/mcp/dub-partners.",
    ),
    (
        "dux_soup",
        "official",
        "https://www.dux-soup.com/blog/dux-soup-mcp-use-ai-to-control-your-linkedin-automation",
        "Official + aggregator. Also zapier.com/mcp/dux-soup.",
    ),
    (
        "dynamic_content_snippet",
        "none",
        "",
        "Likely a feature name, not a standalone vendor.",
    ),
    (
        "dynapictures",
        "aggregator",
        "https://zapier.com/mcp/dynapictures",
        "No official MCP.",
    ),
    (
        "egoi",
        "none",
        "https://e-goi.com/en/developers/",
        "General API docs. No MCP.",
    ),
    (
        "easypromos",
        "none",
        "https://developers.easypromosapp.com/",
        "General API docs. No MCP.",
    ),
    (
        "easysendy",
        "aggregator",
        "https://zapier.com/mcp/easysendy-pro-da35212",
        "No official vendor MCP.",
    ),
    (
        "echtpost_postcards",
        "aggregator",
        "https://mcp.composio.dev/echtpost",
        "Composio toolkit.",
    ),
    ("ecologi", "none", "https://ecologi.com/", "No public API found."),
    (
        "elastic_email",
        "official",
        "https://github.com/ElasticEmail/elasticemail-mcp-server",
        "Dotobot uses mcp.elasticemail.com/mcp.",
    ),
    (
        "email_on_acid",
        "community",
        "https://glama.ai/mcp/servers/KnakLabs/email-on-acid-mcp",
        "Third-party (KnakLabs).",
    ),
    ("emailable", "none", "https://emailable.com/docs/api", "No dedicated MCP."),
    ("emailchef", "none", "https://www.emailchef.com/", "No dedicated MCP."),
    (
        "emaillistverify",
        "official",
        "https://emaillistverify.com/mcp-server",
        "Vendor MCP. Also on Pipedream/Composio.",
    ),
    (
        "emailoctopus",
        "aggregator",
        "https://composio.dev/toolkits/emailoctopus",
        "No official vendor server.",
    ),
    (
        "emailverify_io",
        "official",
        "https://www.emailverify.io/mcp/",
        "Vendor-published MCP.",
    ),
    (
        "emelia",
        "aggregator",
        "https://composio.dev/toolkits/emelia",
        "Composio toolkit only.",
    ),
    (
        "encharge",
        "aggregator",
        "https://zapier.com/mcp/encharge",
        "Zapier/viaSocket only.",
    ),
    ("endorsal", "none", "https://endorsal.io/", "No MCP found."),
    ("engage", "none", "", "Too generic to identify a specific vendor."),
    (
        "enginemailer",
        "community",
        "https://www.npmjs.com/package/@lightyoruichi/enginemailer-mcp",
        "Third-party npm package.",
    ),
    (
        "enormail",
        "aggregator",
        "https://zapier.com/mcp/enormail",
        "Zapier/viaSocket only.",
    ),
    (
        "esputnik",
        "aggregator",
        "https://zapier.com/mcp/esputnik",
        "Composio/Zapier/viaSocket.",
    ),
    (
        "eventbrite",
        "community",
        "https://github.com/joshuachestang/eventbrite-mcp-server",
        "Several independent repos exist.",
    ),
    (
        "everwebinar",
        "aggregator",
        "https://zapier.com/mcp/webinarjam",
        "Listed jointly with WebinarJam.",
    ),
    ("exact_mails", "none", "https://exactmails.com/", "No dedicated MCP."),
    (
        "ez_texting",
        "official",
        "https://mcp.eztexting.com/",
        "Dotobot uses mcp.eztexting.com/mcp.",
    ),
    (
        "facebook",
        "aggregator",
        "https://zapier.com/mcp/facebook-pages",
        "Also community repos; no official Meta server.",
    ),
    (
        "feedblitz",
        "none",
        "https://developer.feedblitz.com/",
        "REST API, no MCP.",
    ),
    (
        "figma",
        "official",
        "https://developers.figma.com/docs/figma-mcp-server/",
        "Dev Mode MCP Server. Community alt: github.com/GLips/Figma-Context-MCP.",
    ),
    (
        "flexmail",
        "partial",
        "https://www.mcpbundles.com/skills/flexmail",
        "Fallback API docs: developer.flexmail.eu.",
    ),
    (
        "flippingbook",
        "none",
        "https://flippingbook.com/help/publisher-2",
        "No MCP found.",
    ),
    (
        "fomo",
        "aggregator",
        "https://composio.dev/toolkits/fomo",
        "Also listed at mcp.ai/fomo.",
    ),
    (
        "freshmarketer",
        "partial",
        "https://developers.freshworks.com/docs/agentic-dev-tools/mcp-server/",
        "Freshworks MCP gateway covers Freshmarketer.",
    ),
    (
        "front",
        "official",
        "https://help.front.com/en/articles/4883136",
        "Dotobot uses mcp.frontapp.com/mcp.",
    ),
    (
        "frontify",
        "official",
        "https://www.frontify.com/en/blog/frontify-mcp",
        "Dotobot uses mcp.frontify-integrations.com/mcp.",
    ),
    (
        "fullenrich",
        "official",
        "https://fullenrich.com/mcp",
        "Dotobot uses mcp.fullenrich.com/mcp.",
    ),
    (
        "funnelcockpit",
        "aggregator",
        "https://zapier.com/mcp/funnelcockpit",
        "No vendor-native server.",
    ),
    ("getemails", "none", "https://getemails.com/", "No dedicated MCP found."),
    (
        "getresponse",
        "partial",
        "https://zapier.com/mcp/getresponse",
        "Fallback API docs: apidocs.getresponse.com.",
    ),
    (
        "getswift",
        "aggregator",
        "https://zapier.com/mcp/getswift",
        "No official vendor server.",
    ),
    ("giantcampaign", "none", "https://www.giantcampaign.com/", "No known MCP server."),
    (
        "gist",
        "partial",
        "https://composio.dev/toolkits/gist",
        "No official vendor server.",
    ),
    (
        "github",
        "official",
        "https://github.com/settings/personal-access-tokens",
        "REST with a personal access token, not Copilot MCP. Classic: repo "
        "(private) or public_repo (public only). Fine-grained: Issues and "
        "Pull requests read/write on the repos bots should use. Optional org "
        "is the default owner for a bare repo name.",
    ),
    (
        "gitter",
        "none",
        "https://developer.gitter.im/docs/",
        "Largely legacy / merged into Matrix/Element.",
    ),
    (
        "gmail",
        "official",
        "https://myaccount.google.com/apppasswords",
        "Signs in with a Google app password over IMAP and SMTP — no Google Cloud project, OAuth client, or consent screen. 1. Turn on 2-Step Verification for the Google account (Google Account → Security). 2. Open the app passwords page (link below), enter a name such as Harness, and tap Create. 3. Paste the Gmail address and the 16-character password shown here. Bots search and read mail and attachments (PDF text extraction included), draft, and send. Each inbox is its own account: Add another account for a second address.",
    ),
    ("gobio_link", "none", "https://gobio.link/", "No known MCP or public API docs."),
    ("goodbits", "none", "https://goodbits.io/", "No known MCP server."),
    (
        "google_ad_manager",
        "community",
        "https://github.com/MatiousCorp/google-ad-manager-mcp",
        "No official Google-published GAM MCP.",
    ),
    (
        "google_ads",
        "official",
        "https://developers.google.com/google-ads/api/docs/developer-toolkit/mcp-server",
        "Official. Announced Oct 2025.",
    ),
    (
        "google_analytics",
        "official",
        "https://developers.google.com/analytics/devguides/MCP",
        "Official GA4 MCP server.",
    ),
    (
        "google_calendar",
        "community",
        "https://github.com/nspady/google-calendar-mcp",
        "No official Google server; most-used community one.",
    ),
    (
        "google_drive",
        "official",
        "https://developers.google.com/workspace/drive/api/guides/configure-mcp-server",
        "Originated in modelcontextprotocol/servers-archived.",
    ),
    (
        "google_sheets",
        "community",
        "https://github.com/xing5/mcp-google-sheets",
        "Google also has a config guide at developers.google.com/workspace/sheets.",
    ),
    (
        "gosquared",
        "aggregator",
        "https://composio.dev/toolkits/gosquared",
        "No dedicated vendor server.",
    ),
    (
        "gozen_growth",
        "aggregator",
        "https://zapier.com/mcp/gozen-growth",
        "Also Composio toolkit.",
    ),
    ("grade_us", "none", "https://gradeus.com/", "No public docs surfaced."),
    (
        "greenspark",
        "none",
        "https://www.getgreenspark.com/",
        "No API docs surfaced.",
    ),
    (
        "growsurf",
        "none",
        "https://docs.growsurf.com/developer-tools/rest-api",
        "REST API + JS SDK, no MCP.",
    ),
    (
        "handwrytten",
        "official",
        "https://mcp.handwrytten.com/",
        "Dotobot uses mcp.handwrytten.com/mcp.",
    ),
    ("herobot", "none", "https://herobot.app/", "No developer API docs surfaced."),
    (
        "heyreach",
        "community",
        "https://github.com/bcharleson/heyreach-mcp",
        "Dotobot uses mcp.heyreach.io/mcp.",
    ),
    (
        "heysummit",
        "aggregator",
        "https://zapier.com/mcp/heysummit",
        "No dedicated server found.",
    ),
    (
        "hippo_video",
        "none",
        "https://help.hippovideo.io/",
        "No API/MCP docs surfaced.",
    ),
    (
        "hubspot",
        "official",
        "https://developers.hubspot.com/mcp",
        "Official public beta. Dotobot uses mcp.hubspot.com/anthropic.",
    ),
    (
        "humanitix",
        "aggregator",
        "https://composio.dev/toolkits/humanitix",
        "No dedicated vendor server.",
    ),
    (
        "hygraph",
        "official",
        "https://hygraph.com/docs/hygraph-ai/mcp-server",
        "Dotobot uses mcp.hygraph.com/mcp.",
    ),
    (
        "hypeauditor",
        "aggregator",
        "https://composio.dev/toolkits/hypeauditor",
        "Also via Zapier.",
    ),
    (
        "hyperise",
        "aggregator",
        "https://composio.dev/toolkits/hyperise",
        "No dedicated vendor server.",
    ),
    ("icontact", "none", "https://www.icontact.com/", "No API/MCP docs surfaced."),
    (
        "impression",
        "none",
        "https://www.impressiondigital.com/",
        "No public API or MCP found.",
    ),
    (
        "indiefunnels",
        "none",
        "https://pipedream.com/apps/indiefunnels",
        "Generic Pipedream connector only.",
    ),
    (
        "infusionsoft",
        "community",
        "https://github.com/saxyguy81/mcp-keap",
        "No official Keap-published MCP.",
    ),
    (
        "inksprout",
        "none",
        "https://inksprout.co/docs/index.html",
        "Only Zapier generic wrapper.",
    ),
    (
        "instabot",
        "none",
        "https://zapier.com/mcp/instabot",
        "Only Zapier generic wrapper.",
    ),
    (
        "instagram",
        "community",
        "https://github.com/AleemHaider/instagram-mcp",
        "Meta has no official server; Composio/Apify also offer wrappers.",
    ),
    (
        "instantly",
        "official",
        "https://help.instantly.ai/en/articles/12980002-instantly-mcp-model-context-protocol",
        "Dotobot uses mcp.instantly.ai/mcp.",
    ),
    (
        "instasent",
        "none",
        "https://spec.instasent.com/",
        "General API docs only.",
    ),
    (
        "intercom",
        "official",
        "https://developers.intercom.com/docs/guides/mcp",
        "Official. Also github.com/intercom/intercom-mcp-server.",
    ),
    ("jellyreach", "none", "", "No clear public docs found."),
    (
        "jira",
        "official",
        "https://github.com/atlassian/atlassian-mcp-server",
        "Dotobot uses mcp.atlassian.com/v1/mcp (same server as Atlassian).",
    ),
    (
        "joggai",
        "none",
        "https://docs.jogg.ai/api-reference/QuickStart/GettingStarted",
        "Documented REST API, no MCP.",
    ),
    ("jvzoo", "none", "https://api.jvzoo.com/docs/", "No MCP found."),
    (
        "kartra",
        "none",
        "https://zapier.com/mcp/kartra",
        "Only Zapier/Pipedream generic wrappers.",
    ),
    (
        "kickofflabs",
        "none",
        "https://zapier.com/mcp/kickofflabs",
        "Only Zapier generic wrapper.",
    ),
    ("kingsumo", "none", "", "No public API docs site found."),
    (
        "klaviyo",
        "official",
        "https://developers.klaviyo.com/en/docs/klaviyo_mcp_server",
        "Dotobot uses mcp.klaviyo.com/mcp.",
    ),
    ("klenty", "none", "https://www.klenty.com/", "No dedicated MCP found."),
    (
        "kyvio",
        "none",
        "https://zapier.com/mcp/kyvio2",
        "Only Zapier generic wrapper.",
    ),
    (
        "lagrowthmachine",
        "community",
        "https://lobehub.com/mcp/gigradar-lgm-mcp-server",
        "Also via Composio; no official vendor server confirmed.",
    ),
    ("lahar", "none", "", "No vendor API docs surfaced."),
    (
        "laposta",
        "none",
        "https://developer.laposta.nl/",
        "No MCP found.",
    ),
    (
        "lawmatics",
        "none",
        "https://help.lawmatics.com/en/articles/10699986-lawmatics-zapier-app-overview",
        "Only classic Zapier zaps.",
    ),
    (
        "lead_identity_check",
        "aggregator",
        "https://zapier.com/mcp/lead-identity-check",
        "Phone/address/email-to-name verification.",
    ),
    (
        "leaddyno",
        "none",
        "https://leaddyno.com/api_docs",
        "Only classic Zapier integration.",
    ),
    (
        "leadoku",
        "aggregator",
        "https://composio.dev/toolkits/leadoku/framework/claude-code",
        "Composio-hosted.",
    ),
    (
        "leadpops",
        "none",
        "https://zapier.com/apps/leadpops-leads/integrations",
        "Only classic Zapier integrations.",
    ),
    (
        "linear",
        "official",
        "https://linear.app/docs/mcp",
        "Linear-hosted remote MCP. Dotobot uses mcp.linear.app/mcp.",
    ),
    (
        "linkedin",
        "community",
        "https://github.com/stickerdaniel/linkedin-mcp-server",
        "No official LinkedIn MCP.",
    ),
    (
        "mailchimp",
        "none",
        "https://mailchimp.com/developer/marketing/api/",
        "No confirmed well-known MCP; use Marketing API.",
    ),
    (
        "microsoft_excel",
        "community",
        "https://github.com/haris-musa/excel-mcp-server",
        "Community (~4.1k stars). No official MS Excel MCP.",
    ),
    (
        "microsoft_outlook",
        "official",
        "https://github.com/microsoft/mcp",
        "Microsoft 365 Mail MCP (Graph API).",
    ),
    (
        "microsoft_teams",
        "official",
        "https://github.com/microsoft/mcp",
        "Microsoft 365 Teams MCP (Graph API).",
    ),
    (
        "monday",
        "official",
        "https://developer.monday.com/apps/docs/mondaycom-mcp-integration",
        "Official. Open-source impl: github.com/mondaycom/monday-ai.",
    ),
    (
        "notion",
        "official",
        "https://developers.notion.com/docs/mcp",
        "Notion-hosted remote MCP via OAuth. Dotobot uses mcp.notion.com/mcp.",
    ),
    (
        "openai",
        "none",
        "https://platform.openai.com/docs/api-reference",
        "Primarily an MCP client/host, not a server. This is a provider, not a service MCP.",
    ),
    (
        "pipedrive",
        "aggregator",
        "https://composio.dev/toolkits/pipedrive",
        "Dotobot uses mcp.pipedrive.com/mcp.",
    ),
    (
        "quickbooks",
        "aggregator",
        "https://composio.dev/toolkits/quickbooks",
        "105 tools; no official Intuit-published MCP.",
    ),
    (
        "salesforce",
        "official",
        "https://github.com/salesforcecli/mcp",
        "Salesforce DX MCP Server (npm: @salesforce/mcp).",
    ),
    (
        "shopify",
        "official",
        "https://shopify.dev/docs/apps/build/storefront-mcp",
        "Storefront + Customer Accounts MCP. Dotobot uses https://{store_domain}/api/mcp.",
    ),
    (
        "slack",
        "community",
        "https://github.com/korotovsky/slack-mcp-server",
        "Table lists a community server; harness already uses official mcp.slack.com/mcp.",
    ),
    (
        "stripe",
        "official",
        "https://docs.stripe.com/mcp",
        "Official. Hosted at mcp.stripe.com.",
    ),
    (
        "telegram",
        "community",
        "https://github.com/sparfenyuk/mcp-telegram",
        "No official Telegram MCP.",
    ),
    (
        "trello",
        "official",
        "https://github.com/atlassian/trello-mcp-server",
        "Dotobot uses mcp.trello.com/v1.",
    ),
    (
        "twilio",
        "official",
        "https://github.com/twilio-labs/mcp",
        "Official. Docs: twilio.com/docs/ai/mcp.",
    ),
    (
        "typeform",
        "official",
        "https://www.typeform.com/developers/mcp/",
        "Dotobot uses api.typeform.com/mcp.",
    ),
    (
        "whatsapp",
        "none",
        "https://developers.facebook.com/docs/whatsapp/",
        "No official Meta MCP; unofficial community servers exist.",
    ),
    (
        "woocommerce",
        "official",
        "https://developer.woocommerce.com/docs/features/mcp/",
        "Official beta as of late 2025.",
    ),
    (
        "xero",
        "official",
        "https://github.com/XeroAPI/xero-mcp-server",
        "Dotobot uses mcp.xero.com/mcp.",
    ),
    (
        "zendesk",
        "none",
        "https://developer.zendesk.com/api-reference/",
        "No official vendor MCP; community + Zapier only.",
    ),
    (
        "zoom",
        "official",
        "https://developers.zoom.us/docs/mcp/",
        "Official. Dotobot uses mcp.zoom.us/mcp/meeting/streamable.",
    ),
    # Live catalog types that were not in the HeyMarcus table.
    (
        "ahrefs",
        "official",
        "https://docs.ahrefs.com/mcp/docs/introduction",
        "Official hosted MCP at api.ahrefs.com/mcp/mcp. Streamable HTTP + OAuth. Lite plan or higher.",
    ),
    (
        "granola",
        "official",
        "https://docs.granola.ai/help-center/sharing/integrations/mcp",
        "Official hosted MCP at mcp.granola.ai/mcp.",
    ),
    (
        "n8n",
        "official",
        "https://docs.n8n.io/advanced-ai/mcp/accessing-n8n-mcp-server/",
        "Instance MCP at https://{host}/mcp-server/http. OAuth or bearer token. Enable in Settings → Instance-level MCP.",
    ),
    (
        "triggerdev",
        "none",
        "https://trigger.dev/docs/mcp-introduction",
        "Official MCP is CLI stdio only (npx trigger.dev@latest mcp). No hosted HTTP URL.",
    ),
    (
        "1password",
        "none",
        "https://www.1password.dev/environments/mcp-server",
        "Official MCP is local stdio only (1password-mcp via the desktop app). No hosted HTTP URL. www.1password.dev/mcp is Mintlify docs search, not vaults.",
    ),
    (
        "google",
        "none",
        "https://developers.google.com/workspace",
        "Umbrella Google stub. Prefer the Gmail / Calendar / Drive / Sheets / Ads entries.",
    ),
    (
        "cloudflare",
        "official",
        "https://developers.cloudflare.com/agents/model-context-protocol/cloudflare/servers-for-cloudflare/",
        "Dotobot uses mcp.cloudflare.com/mcp (OAuth, or a pasted API token as bearer).",
    ),
    (
        "paypal",
        "official",
        "https://developer.paypal.com/",
        "Dotobot uses mcp.paypal.com/mcp.",
    ),
    (
        "square",
        "official",
        "https://developer.squareup.com/",
        "Dotobot uses mcp.squareup.com/mcp.",
    ),
    (
        "sentry",
        "official",
        "https://docs.sentry.io/",
        "Dotobot uses mcp.sentry.dev/mcp.",
    ),
    (
        "vercel",
        "official",
        "https://vercel.com/docs",
        "Dotobot uses mcp.vercel.com.",
    ),
    (
        "posthog",
        "official",
        "https://posthog.com/docs",
        "Dotobot uses mcp.posthog.com/mcp.",
    ),
    (
        "amplitude",
        "official",
        "https://amplitude.com/docs",
        "Dotobot uses mcp.amplitude.com/mcp.",
    ),
    (
        "miro",
        "official",
        "https://developers.miro.com/",
        "Dotobot uses mcp.miro.com/.",
    ),
    (
        "canva",
        "official",
        "https://www.canva.dev/docs/connect/",
        "Dotobot uses mcp.canva.com/mcp.",
    ),
    (
        "webflow",
        "official",
        "https://developers.webflow.com/mcp/reference/overview",
        "Dotobot uses mcp.webflow.com/mcp.",
    ),
    (
        "zapier",
        "official",
        "https://zapier.com/mcp",
        "Dotobot uses mcp.zapier.com/api/v1/connect.",
    ),
    (
        "composio",
        "official",
        "https://docs.composio.dev/docs/composio-connect",
        "Official hosted MCP at connect.composio.dev/mcp. Streamable HTTP + OAuth. Seven meta-tools over 1000+ apps.",
    ),
    (
        "atlassian",
        "official",
        "https://github.com/atlassian/atlassian-mcp-server",
        "Rovo MCP. Dotobot uses mcp.atlassian.com/v1/mcp. Jira is also a separate gallery stub.",
    ),
]

DOCS: dict[str, dict[str, str]] = {}
for _type, _publisher, _docs, _notes in _ROWS:
    if _type in DOCS:
        raise ValueError(f"duplicate connector_docs type {_type}")
    DOCS[_type] = {"publisher": _publisher, "docs": _docs, "notes": _notes}
