"""Setup notes for each catalog connector: docs URL, MCP publisher, comments.

Merged onto catalog() rows as `docs` / `publisher` / `notes`. Publisher is
`official`, `community`, `aggregator`, `partial`, or `none`. Aggregator means
Zapier / Composio / Pipedream — not a first-party MCP URL we can OAuth to.
"""

from __future__ import annotations

# type, publisher, docs URL, notes
_ROWS: list[tuple[str, str, str, str]] = [
    (
        "360nrs",
        "official",
        "https://apidocs.360nrs.com/",
        "Store username:apiPassword as the secret, using the API password, not the platform login password. Allow the server IP in 360NRS settings. Paths are relative to https://dashboard.360nrs.com/api/rest; HTTP Basic authentication is used.",
    ),
    (
        "4dem",
        "official",
        "https://api.4dem.it/open-api",
        "Store the 4Dem API key. The connector exchanges it at /authenticate for a bearer token before every request. Paths are relative to https://api.4dem.it, for example /addressbook/. Dedicated and partner API-channel hosts are not covered.",
    ),
    (
        "abyssale",
        "official",
        "https://developers.abyssale.com/rest-api/quickstart",
        "Store a workspace API key. REST paths are relative to https://api.abyssale.com; for example GET /designs. Authentication uses x-api-key.",
    ),
    (
        "acelle_mail",
        "official",
        "https://acellesend.com/rest-api",
        "Set instance_domain to the HTTPS hostname of your Acelle Mail installation, without a scheme or path. Store the API token from My Profile > API and Authentication. Paths are relative to /api/v1, for example /me. Authentication uses Bearer. Installations under a URL subdirectory are not covered.",
    ),
    (
        "activecampaign",
        "official",
        "https://developers.activecampaign.com/reference/authentication",
        "Set api_domain to the host from Settings > Developer API URL, without https:// or /api/3. Do not guess the region. Store the API token. Paths are relative to /api/3, for example /users/me; authentication uses Api-Token.",
    ),
    (
        "active_trail",
        "official",
        "https://webapi.mymarketing.co.il/api/docs/Guides",
        "Store the access token from Settings > API apps. The token is sent unchanged in Authorization. Paths are relative to https://webapi.mymarketing.co.il/api, for example /groups. Check token expiry and allowed IPs.",
    ),
    (
        "acumbamail",
        "official",
        "https://acumbamail.com/apidoc/",
        "Store the auth token from My account > Preferences. Dotobot inserts auth_token into GET queries or POST form data from the secret store. Use function paths with trailing slashes, such as /getLists/. JSON is the default response format. Pass POST parameters as a body object; nested fields are form-encoded with bracket notation. Some GET functions can modify data too: select functions carefully. Do not include auth_token in tool arguments.",
    ),
    (
        "acymailing",
        "official",
        "https://docs.acymailing.com/rest-api",
        "AcyMailing 9.2.0+ Essential or higher on Joomla/WordPress; enable REST API in Security settings. Configure api_domain as the website hostname, store its license key (Api-Key header). Call /index.php?page=acymailing_front&option=com_acym&ctrl=api&task=getUsers; include any installation subdirectory in the path. POST operations use JSON. Subscription operations default to sending emails and triggering automations unless disabled in their body. Endpoint docs specify Api-Key despite the overview describing Basic authentication.",
    ),
    (
        "add_to_calendar_pro",
        "official",
        "https://docs.add-to-calendar-pro.com/api/introduction",
        "Organization API key in Authorization without a prefix. Read/write scopes and expiry apply. GET /event/all supports page; POST /event takes event_group (or new_event_group_name) and dates. Creation publishes immediately; updates may consume event credits. PATCH /event/PROKEY updates fields. Binary ICS downloads use a separate host.",
    ),
    (
        "adhook",
        "official",
        "https://app.adhook.io/api-doc/",
        "Store a current Adhook JWT access token, sent as Bearer. The provider web client supplies the /api base prefix omitted by its OpenAPI schema. Include /v1 or /v2 in paths, e.g. GET /v1/notifications/count. JSON bodies are supported. Shared-view adhookToken credentials are a separate mechanism and are not supported by this route. Token creation/refresh and authenticated account acceptance remain open.",
    ),
    (
        "adrapid",
        "official",
        "https://user-api-docs.adrapid.com/",
        "Store the account API token (JWT Bearer). The current OpenAPI server uses /v1/api, unlike abbreviated overview examples. GET /me reads account data. POST /banners takes JSON templateId and modes, such as png=true. Poll /banners/ID until status is ready and inspect files. Banner creation and completed export are separate; binary downloads are not handled by this JSON tool.",
    ),
    (
        "adroll",
        "official",
        "https://apidocs.nextroll.com/guides/get-started.html",
        "Store a Personal Access Token; sent as Authorization: Token. Supply the developer application client ID as apikey in the URL query on every request (GET query or POST path query). GET /api/v1/organization/get_advertisables lists brands. CRUD writes use multipart scalar form fields; file uploads and nested bodies are unsupported. Paths include the service/version. OAuth flow is not implemented. Campaign changes may spend advertising budget.",
    ),
    (
        "adtraction",
        "official",
        "https://apidocs.adtraction.net/nextgen/",
        "Store the API token from Adtraction Account > Settings > API. Uses X-Token authentication and JSON bodies. Include the API version in each path: GET /v2/partner/markets/ or POST /v3/partner/programs/ with market in the JSON body. Both v2 and v3 share the configured host; prefer v3 replacements for deprecated v2 endpoints. Keep documented trailing slashes. Pagination starts at page 0.",
    ),
    (
        "aimtell",
        "official",
        "https://developers.aimtell.com/api-reference/introduction",
        "REST API key goes in X-Authorization-Api-Key. Paths are relative to /prod. GET /sites/ lists websites with limit/skip pagination; PUT /site/ID takes JSON name and optional icon. Campaign and subscriber operations can send pushes or trigger automations. Inspect result/message as well as HTTP status.",
    ),
    (
        "airship",
        "official",
        "https://www.airship.com/docs/developer/rest-api/ua/introduction/",
        "Set region to us or eu (default us) and auth_mode to bearer, basic or oauth (default bearer). Store a dashboard token for bearer, appKey:appSecret or appKey:masterSecret for basic, or a current OAuth access token for oauth. Dotobot selects the matching regional HTTP or OAuth host and sends the required version-3 Accept header. Include /api in paths, for example GET /api/channels. Roles and scopes limit access. OAuth token creation and refresh are not implemented. JSON requests are supported; CSV uploads are not. Messaging endpoints can deliver to real audiences.",
    ),
    (
        "airtable",
        "official",
        "https://support.airtable.com/articles/9897799762-using-the-airtable-mcp-server",
        "Official MCP. Popular alt: github.com/domdomegg/airtable-mcp-server.",
    ),
    (
        "amazon_advertising",
        "official",
        "https://advertising.amazon.com/library/news/amazon-ads-mcp-server-open-beta",
        "Dotobot uses advertising-ai.amazon.com/mcp.",
    ),
    (
        "anthropic",
        "none",
        "https://github.com/modelcontextprotocol/servers",
        "Anthropic authored the MCP spec and reference servers; this is a provider, not a service MCP.",
    ),
    (
        "apexverify",
        "official",
        "https://documentation.apexverify.com/api-reference/api-authentication",
        "Store an ApexVerify API key, sent in X-Api-Key. GET /account/credits reads the balance. POST /unit accepts JSON type (email or phone), target_country and unit. Verification consumes credits; review use_global_cache before submitting data. Multipart batch uploads and binary exports are not supported by the generic JSON tool.",
    ),
    (
        "appsflyer",
        "official",
        "https://dev.appsflyer.com/hc/reference/app-list-ad-nets-api-get",
        "Store a current API V2 token as Bearer, not an SDK dev key. GET /api/mng/apps lists accessible apps; use limit and offset to page results. Include each endpoint service/version in path. JSON requests on hq1 are supported, including POST /api/p360-click-signing/v2.0/test with url and signature_version. Other service hosts, binary exports and token issuance are not covered. Account permissions and endpoint quotas apply.",
    ),
    (
        "arpoone",
        "official",
        "https://docs.arpoone.com/api-reference/",
        "Store the User Settings API key, sent as Bearer. Paths are relative to /v1.2. POST /balance/currentbalance takes JSON organizationIds; POST /shorturl takes organizationId and items containing url. Organization IDs belong in operation bodies. Audience operations require an audience schema first. Messaging and balance transfers have external effects; inspect response codes and per-item results.",
    ),
    (
        "asana",
        "official",
        "https://developers.asana.com/docs/mcp-server",
        "Vendor-hosted remote MCP.",
    ),
    (
        "asters",
        "official",
        "https://docs.asters.ai/api",
        "Store the workspace settings API key; sent in x-api-key. All requests include JSON Content-Type and Accept. GET /workspaces lists available workspaces. POST /data/posts reads posts using socialAccountId, page and optional filters.date from/to in MM-DD-YYYY format. Inspect error and data fields. Separate S3 media downloads are not part of this route. Live invalid-key response names x-asters-key instead of the documented x-api-key; authentication remains unresolved.",
    ),
    (
        "attentive",
        "official",
        "https://docs.attentive.com/docs/authentication",
        "Store the private application API key. Paths are relative to https://api.attentivemobile.com/v1; GET /subscriptions needs an email or phone query. Authentication uses Bearer.",
    ),
    (
        "autoklose",
        "official",
        "https://www.postman.com/cloudy-space-2757/autoklose-s-public-workspace/documentation/twa9gic/autoklose-api",
        "Generate an API token under Integrations. Sent as the api_token URL query parameter on all methods. JSON request bodies; use page for paginated reads and expand or expand[] for supported related data. Paths are relative to /api. Campaign status updates can start email delivery. Binary attachment downloads and multipart uploads are unsupported.",
    ),
    (
        "automizy",
        "official",
        "https://github.com/Automizy/Automizy-Js-Api",
        "Uses the published vendor SDK host api.automizy.com and Bearer token authentication. Include /v2 in paths. GET /v2/smart-lists/ID/contacts reads list contacts; POST that path takes JSON contacts containing IDs or emails. Contact changes may trigger automations. This is the legacy SDK contract: current account acceptance is unverified, and the separate gateway.automizy.com host times out. Token refresh is not implemented.",
    ),
    (
        "aweber",
        "official",
        "https://docs.aweber.com/integrations/integrations/aweber-mcp-integration-ai-powered-email-marketing-management",
        "Dotobot uses mcp.aweber.com/mcp.",
    ),
    (
        "beamer",
        "official",
        "https://www.getbeamer.com/help/how-to-use-single-user-notifications",
        "Store a Beamer API key from Settings > API. Paths are relative to /v0, for example GET /posts or POST /posts with a JSON body. Authentication uses Beamer-Api-Key. Key permissions control read and write access.",
    ),
    (
        "beehiiv",
        "official",
        "https://www.beehiiv.com/features/mcp",
        "Dotobot uses mcp.beehiiv.com/mcp.",
    ),
    (
        "benchmark_email",
        "official",
        "https://benchmarkemail.github.io/RESTful-API-v3/",
        "Store a Benchmark Email API token. Uses AuthToken and application/json headers, including GET. Read lists with GET /Contact/ and query SearchFilter. Create a list with POST /Contact and body Data containing Name and Description. Response.Status must be 1; HTTP 200 alone can contain an application error. This is REST v3, not the legacy XML API.",
    ),
    (
        "bigmailer",
        "official",
        "https://docs.bigmailer.io/docs/getting-started-api",
        "Store a BigMailer API key. Paths are relative to https://api.bigmailer.io/v1, for example /me. Authentication uses X-API-Key and JSON bodies.",
    ),
    (
        "bitly",
        "official",
        "https://dev.bitly.com/bitly-mcp/overview/what-is-mcp",
        "Dotobot uses api-ssl.bitly.com/v4/mcp.",
    ),
    (
        "botconversa",
        "official",
        "https://backend.botconversa.com.br/swagger/",
        "Store a BotConversa API key. Authentication uses API-KEY. Keep endpoint trailing slashes, for example GET /tags/ or /flows/. JSON writes are supported. POST /subscriber/ requires has_opt_in_whatsapp=true and actual contact consent. Messaging and flow endpoints can contact subscribers; adding the route does not authorize outreach.",
    ),
    (
        "brandfetch",
        "official",
        "https://docs.brandfetch.com/mcp/overview",
        "Dotobot uses mcp.brandfetch.io/mcp.",
    ),
    (
        "brandmentions",
        "official",
        "https://help.brandmentions.com/en/articles/12814618-how-do-i-authenticate-api-requests-safely",
        "Store the API key issued by BrandMentions. GET /command.php with query command=GetRemainingCredits checks credits; ListProjects lists projects. Dotobot inserts api_key from the secret store. Commands, including mutations and paid search jobs, share this endpoint; GET does not imply read-only. API access must be enabled by the provider.",
    ),
    (
        "braze",
        "official",
        "https://www.braze.com/docs/user_guide/brazeai/mcp_server",
        "Dotobot uses mcp.braze.com/mcp.",
    ),
    (
        "builderall_mailingboss",
        "official",
        "https://knowledgebase.builderall.com/docs/mailingboss-5-0-api-integration/",
        "Store the MailingBoss 5.0 Integration Key. Dotobot appends it as an encoded final path segment; omit the token from tool paths. GET /lists retrieves lists; POST /lists/fields with list_uid retrieves fields. Subscriber operations accept JSON body fields. Inspect status and data; subscriber creation may trigger configured automation.",
    ),
    (
        "buysellads",
        "official",
        "https://docs.buysellads.com/advertiser-api",
        "Request a private API key from your account manager. Sent as the key query parameter. Advertiser reporting GET paths: /lineitems, /daily-stats, /creatives, /creatives-daily-stats. Use startDate/endDate in YYYY-MM-DD format (UTC) to bound results; there is no pagination. Optional type=csv returns text. This is the Advertiser API, not the separate ad-serving service. No write endpoints are documented.",
    ),
    (
        "calendly",
        "official",
        "https://developer.calendly.com/calendly-mcp-server",
        "Dotobot uses mcp.calendly.com.",
    ),
    (
        "callpage",
        "official",
        "https://callpage.github.io/documentation-rest/",
        "Store the dashboard API key; sent directly in Authorization. GET /v3/external/calls/history reads history. Include the documented version in each path; field updates use PATCH /v1/external/calls/CALL_ID/fields/FIELD_ID with JSON value. Inspect hasError and data. Token/widget scopes apply. Calling and messaging endpoints can contact people.",
    ),
    (
        "callrail",
        "official",
        "https://apidocs.callrail.com/",
        "Store a CallRail API key. Paths are relative to https://api.callrail.com/v3, for example GET /a.json. Authentication uses Authorization: Token token=KEY.",
    ),
    (
        "campaign_cleaner",
        "official",
        "https://docs.campaigncleaner.com/api-reference/endpoint/get-credits",
        "Store a Campaign Cleaner API key. Authentication uses X-CC-API-Key. GET /get_credits reads the credit balance. POST /send_campaign accepts a send_campaign object with campaign_html and campaign_name; this submits analysis and consumes credits. Poll the campaign status before retrieving results. JSON endpoints are supported; binary PDF responses are not.",
    ),
    (
        "campaign_monitor",
        "official",
        "https://www.campaignmonitor.com/api/v3-3/getting-started/",
        "Store only the Campaign Monitor API key. HTTP Basic uses it as username with an empty password. Paths are relative to https://api.createsend.com/api/v3.3; use .json endpoints such as /clients.json.",
    ),
    (
        "campaignhq",
        "none",
        "https://campaignhq.docs.apiary.io/",
        "REST uses a stored Bearer API key from Settings > Integrations > API keys. Paths omit /api/v1. GET /lists; POST /lists with JSON name and optional partner_entity_id.",
    ),
    (
        "campayn",
        "official",
        "https://github.com/nebojsac/Campayn-API",
        "Store an API key from the Campayn Account section. Authentication uses Authorization: TRUEREST apikey=KEY. GET /lists.json reads lists. JSON writes such as POST /lists/LIST_ID/contacts.json add contacts; inspect success in the response. Keep the .json endpoint suffix.",
    ),
    (
        "cardly",
        "official",
        "https://api.card.ly/v2/docs",
        "Store a Cardly test_ or live_ API key; use test_ keys to avoid order mutations while testing. Paths are relative to https://api.card.ly/v2, for example /art. Authentication uses API-Key and bodies use text/json as required by Cardly.",
    ),
    (
        "catch_all_verifier",
        "official",
        "https://catchallverifier.readme.io/reference/post_api-v1-verify-single",
        "API Settings key in Authorization without a prefix. GET /credits reads balance. POST /verify/single takes JSON email and optional webhook, consumes credits and returns task id. GET /verify/single?id=TASK retrieves the result. Bulk requests use /verify/bulk; inspect completion status before using results.",
    ),
    (
        "chatrace",
        "official",
        "https://api.chatrace.com/swagger/",
        "Bot account API key in X-ACCESS-TOKEN. GET /accounts/tags reads tags. POST /accounts/tags takes form name; contacts and message bodies use JSON. Dotobot selects form encoding for documented tag, bot-field, contact-field, numeric flow-send, payment and cart paths. Messages and flows contact users; payment/cart operations change orders. Whitelabel partner API is separate.",
    ),
    (
        "cleverreach",
        "official",
        "https://developers.cleverreach.com/docs/api-categories/introduction/",
        "Store a current CleverReach OAuth access token, not the client secret. Authentication uses Bearer. Paths are relative to /v3, for example GET /groups or POST /groups with a JSON name field. OAuth consent and expired-token refresh are not performed by this stored-token route.",
    ),
    (
        "clevertap",
        "official",
        "https://developer.clevertap.com/docs/common-api-components",
        'Set api_domain to the account region: api.clevertap.com (Europe), in1.api.clevertap.com, sg1.api.clevertap.com, us1.api.clevertap.com, aps3.api.clevertap.com, or mec1.api.clevertap.com. Store ["ACCOUNT_ID", "PASSCODE"] as the secret JSON array. GET /1/profile.json?identity=ID reads a profile. POST /1/upload?dryRun=1 validates JSON d profile records without saving; omit dryRun only for intended writes. Inspect status and unprocessed records. APIs requiring a third token, encryption or file uploads are unsupported.',
    ),
    (
        "clickfunnels",
        "official",
        "https://developers.myclickfunnels.com/docs/getting-started",
        "Store a ClickFunnels 2.0 platform application API access token, used as Bearer. Set subdomain to accounts for GET /teams and /teams/TEAM_ID/workspaces; use the actual workspace subdomain for /workspaces/WORKSPACE_ID/contacts and workspace writes. Enter only the subdomain, without scheme or .myclickfunnels.com. Use separate connector records if both scopes are needed. JSON bodies are supported and Dotobot supplies the required User-Agent. Tokens are team-wide. OAuth consent and refresh are not handled here.",
    ),
    (
        "clickup",
        "official",
        "https://developer.clickup.com/docs/connect-an-ai-assistant-to-clickups-mcp-server",
        "Dotobot uses mcp.clickup.com/mcp.",
    ),
    (
        "cloud_convert",
        "official",
        "https://cloudconvert.com/docs/getting-started/introduction",
        "Store a scoped CloudConvert API key. Uses the production https://api.cloudconvert.com/v2 API; GET /users/me requires user.read. Paths omit /v2. Authentication uses Bearer.",
    ),
    (
        "cometly",
        "official",
        "https://docs.cometly.com/introduction/authentication",
        "Store the Cometly API integration key. Authentication uses Bearer; Accept and Content-Type are application/json, including GET requests. Paths are relative to /public-api/v1. GET /events requires start_date and end_date in YYYY-MM-DD HH:MM:SS format in the space timezone. This is the REST API, not the separate MCP endpoint.",
    ),
    (
        "constant_contact",
        "official",
        "https://developer.constantcontact.com/api_guide/getting-started/v3-technical-overview",
        "Store a current Constant Contact V3 OAuth access token. Authentication uses Bearer; paths are relative to /v3, for example GET /contacts. Writes use JSON and require corresponding scopes. OAuth consent and expired-token refresh are not performed by this stored-token route.",
    ),
    (
        "contentdrips",
        "official",
        "https://developer.contentdrips.com/",
        "Store the API Management key; uses Bearer and JSON Content-Type. GET /queue/stats reads queue statistics. POST /render with template_id, output and content_update queues a render; HTTP 202 is acceptance, not completion. Poll /job/JOB_ID/status then /job/JOB_ID/result. Carousel requests use /render?tool=carousel-maker. This is the generation API, not the separate Embed SDK API.",
    ),
    (
        "contentful",
        "official",
        "https://www.contentful.com/developers/docs/tools/mcp-server/",
        "Dotobot uses mcp.contentful.com/mcp.",
    ),
    (
        "convertkit",
        "official",
        "https://developers.kit.com/api-reference/authentication",
        "ConvertKit is now Kit. Store a V4 API key from Developer settings for personal account automation. Authentication uses X-Kit-Api-Key; paths are relative to /v4, for example GET /account. Legacy V3 keys are incompatible. Some endpoints, including bulk and purchase creation, require OAuth and are not covered by this key route.",
    ),
    (
        "copicake",
        "official",
        "https://docs.copicake.com/api/v1-image-get",
        "Store a Copicake API key. Paths are relative to /v1. GET /image/get requires the rendering id query parameter. POST /image/create accepts template_id, changes and options as JSON. Authentication uses Bearer.",
    ),
    (
        "coupontools",
        "official",
        "https://docs.coupontools.com/api/v4/directory",
        'Modern v4 directory and wallet loyalty API. Store credentials as a JSON array ["API_KEY", "API_SECRET"]; sent in x-api-key and x-api-secret. GET /directory lists directories; POST /directory/ID/users uses JSON email and optional profile fields. Legacy coupon/v3 X-Client-Id and X-Client-Secret authentication is not supported by this route.',
    ),
    (
        "crowdpower",
        "official",
        "https://docs.crowdpower.io/getting-started/beacon-api",
        "Store a CrowdPower project secret or application key. Authentication uses Bearer. Uses the Beacon ingestion API, for example POST /customers with user_id and customer fields as JSON, or /customers/bulk with a customers array. This scope provides ingestion, not a documented customer-list GET. Inspect the response success and code fields. Ingestion can trigger configured marketing automations.",
    ),
    (
        "cufinder",
        "official",
        "https://apidoc.cufinder.io/mcp/introduction",
        "Dotobot uses mcp.cufinder.io/mcp.",
    ),
    (
        "curated",
        "official",
        "https://support.curated.co/help/getting-started-with-the-api",
        "Store the Account API Key from the account page. Uses quoted Token token authentication. GET /publications finds publication IDs; POST /publications/ID/issues/ creates a draft. JSON bodies are supported. The API cannot publish issues; use the Curated account interface to publish.",
    ),
    (
        "customer_io",
        "official",
        "https://docs.customer.io/ai/mcp/get-started/",
        "Dotobot uses mcp.customer.io/mcp.",
    ),
    (
        "cyberimpact",
        "official",
        "https://api.cyberimpact.com/docs",
        "Store the JWT API token from Developers > API tokens. Authentication uses Bearer. Paths are relative to https://api.cyberimpact.com; GET /groups reads groups and POST /groups accepts JSON with title and isPublic. Use page and limit for pagination.",
    ),
    (
        "demandbase",
        "official",
        "https://developer.demandbase.com/docs/demandbase-api-overview",
        "Store a current JWT access token generated from an API key set, not a legacy API token or client secret. Uses Bearer and JSON. Tokens expire after eight hours; this route does not issue or refresh them. Include service/version in paths. GET /reporting/v1/usage with apiProduct=b2bapi reads credit usage. POST /data/intent/v1/companies/intent/query takes JSON filters and dates; Intent access is required and the endpoint is beta. Product permissions and quotas apply. Bulk job creation and completed export are separate outcomes.",
    ),
    (
        "demio",
        "aggregator",
        "https://publicdemioapi.docs.apiary.io/",
        "REST credentials are a stored JSON array [API key, API secret]. GET /ping checks authorization; PUT /event/register accepts JSON and can send registration emails. Use sandbox credentials for tests.",
    ),
    (
        "discourse",
        "official",
        "https://docs.discourse.org/",
        "Store an admin-generated API key and configure api_domain (hostname only) and api_username. Uses Api-Key and Api-Username headers. GET /categories.json reads categories; POST /posts.json accepts JSON title and raw to create a topic. User permissions and key scopes apply. Root-host HTTPS installations and ASCII usernames are supported; subdirectory installations, multipart uploads and User API key authorization are not implemented here.",
    ),
    (
        "docupost",
        "official",
        "https://help.docupost.com/developer-documentation/send-letter-api",
        "Store the API token generated on the Developer page. Dotobot inserts api_token into the query. POST /sendletter or /sendpostcard uses URL-encoded non-secret parameters in path, including sender, recipient and document/image URLs. Enable Sandbox Mode in the account token settings for testing. These endpoints send physical mail and may incur charges; no read endpoint is documented here. Never put api_token in tool arguments.",
    ),
    (
        "doppler",
        "official",
        "https://restapi.fromdoppler.com/docs/gettingstarted",
        "Store a Doppler Email Marketing API key from Control Panel > Advanced Preferences. Paths are relative to https://restapi.fromdoppler.com, for example /accounts/ACCOUNT_EMAIL/lists. Authentication uses token KEY. This is not the Doppler secrets product.",
    ),
    (
        "dribbble",
        "official",
        "https://developer.dribbble.com/v2/",
        "Store an OAuth access token, sent as Bearer. GET /user reads the current user; /user/shots lists shots. PUT /shots/ID updates metadata with upload scope. The v2 overview specifies JSON bodies with application/x-www-form-urlencoded Content-Type. OAuth consent and refresh, multipart uploads and binary responses are not implemented here.",
    ),
    (
        "drip",
        "official",
        "https://developer.drip.com/",
        "Store the personal API token. HTTP Basic uses it as username with an empty password. Paths are relative to https://api.getdrip.com and include their version, for example /v2/accounts or /v3/ACCOUNT_ID/shopper_activity/order/batch.",
    ),
    (
        "dripcel",
        "official",
        "https://dripcel.getoutline.com/s/2849f729-5450-4aa3-8cc9-50d29f9f2c74/doc/overview-FaM3SkQan1",
        "Generate a key under Profile > API Keys; sent as Bearer. GET /balance reads credits. POST /contacts/search accepts nested find, projection and options; requires contact.read.pii and costs 10 credits per request. Check the response ok field. Keys have permissions; approximately 50 requests per minute per organisation. Sending and campaign endpoints may deliver messages.",
    ),
    (
        "dropbox",
        "official",
        "https://help.dropbox.com/integrations/connect-dropbox-mcp-server",
        "Dotobot uses mcp.dropbox.com/mcp.",
    ),
    (
        "dropcontact",
        "official",
        "https://developer.dropcontact.com/",
        "Store a Dropcontact access token. Paths are relative to https://api.dropcontact.com/v1/enrich; use /all for enrichment and /webhook for callback configuration. Authentication uses X-Access-Token.",
    ),
    (
        "dub",
        "official",
        "https://dub.co/docs/mcp-server",
        "Dotobot uses mcp.dub.sh/mcp/dub-partners.",
    ),
    (
        "dux_soup",
        "official",
        "https://support.dux-soup.com/article/227-the-dux-soup-api",
        "Turbo or Cloud API: store the Connect-tab Authentication Key and configure numeric userid. Include the user ID in full /xapi/remote/... paths. Dotobot signs GET URLs and JSON bodies with HMAC-SHA1/Base64 in X-Dux-Signature. Non-GET bodies automatically receive targeturl, timestamp and userid; omit those fields from tool arguments. Queue and campaign actions can initiate LinkedIn outreach. Use conversation batch with empty profileids for a no-op read check.",
    ),
    (
        "dynamic_content_snippet",
        "none",
        "https://app.contentsnip.com",
        "ContentSnip API: GET /mappings with x-api-key. The live endpoint distinguishes "
        "missing and invalid keys. Public homepage returns 404; authenticated reads and "
        "write payloads still need account documentation. Updating mappings changes website content.",
    ),
    (
        "dynapictures",
        "official",
        "https://dynapictures.com/docs/",
        "Store a DynaPictures API key. Paths are relative to https://api.dynapictures.com, for example /workspaces or /designs/TEMPLATE_ID. Authentication uses Bearer.",
    ),
    (
        "egoi",
        "official",
        "https://developers.e-goi.com/api/v3/",
        "Store the E-goi API key from account settings. Paths are relative to https://api.egoiapp.com, for example /my-account; do not add /v3. Authentication uses Apikey.",
    ),
    (
        "easypromos",
        "official",
        "https://easypromos-apiref.redoc.ly/",
        "Store an access token from the Easypromos account Utilities menu. Uses Bearer authentication; White Label or Corporate plan required. GET /promotions lists promotions; use paging.next_cursor for further pages. POST requests use JSON. Some participation operations also require a participant login token in the body. Legacy v1 endpoints are retired.",
    ),
    (
        "easysendy",
        "official",
        "https://easysendy.com/email-campaigns/subscriber-management-api/",
        "EasySendy Pro JSON REST API over HTTPS. Store the API key; Dotobot inserts api_key into POST JSON. Reads also use POST: /subscribers_list/lists with empty body, /subscriber/status with list and EMAIL. POST /subscriber/addMultiple takes list and subscribers array. Subscription writes may send confirmation emails. Older /ver4 form endpoints are outside this route. Empty OK responses do not prove authentication.",
    ),
    (
        "echtpost_postcards",
        "aggregator",
        "https://api.echtpost.de/v2/docs",
        "Store a Bearer API key. Use an ep_test_ sandbox key for testing; live keys can incur printing and postage charges. Paths omit /v2. GET /me; POST /cards/preview_fit checks text layout. Card creation, printing and delivery are separate outcomes.",
    ),
    (
        "ecologi",
        "official",
        "https://docs.ecologi.com/",
        "Store the Ecologi Impact API key; authentication uses Bearer. Paths are relative to https://public.ecologi.com. POST /impact/trees takes a JSON number and test flag. Set test to true for non-billable test requests; live impact purchases are billed. Public reporting uses GET /users/USERNAME/trees and does not require authentication at the provider, although this connector currently requires a stored key. Idempotency-Key headers are not exposed; do not automatically retry purchase requests.",
    ),
    (
        "elastic_email",
        "official",
        "https://github.com/ElasticEmail/elasticemail-mcp-server",
        "Dotobot uses mcp.elasticemail.com/mcp.",
    ),
    (
        "email_on_acid",
        "official",
        "https://api.emailonacid.com/docs/latest",
        "Store api_key:account_password as the secret for HTTP Basic authentication. Paths are relative to https://api.emailonacid.com/v5, for example /auth. The documented public sandbox uses sandbox:sandbox.",
    ),
    (
        "emailable",
        "official",
        "https://emailable.com/docs/api/authentication/",
        "Store an Emailable private API key or OAuth access token. Paths are relative to https://api.emailable.com/v1, for example /account. Authentication uses Bearer; public keys only allow verification. Test keys simulate verification without using credits.",
    ),
    (
        "emailchef",
        "official",
        "https://emailchef.com/integration/",
        "Store a current authentication token, sent in authkey. GET /lists uses limit/offset. POST /lists takes JSON instance_in with list_name and optional list_description. Automatic login/token renewal and the separate consumerKey/consumerSecret header pair are not supported. Subscriber writes may trigger flows; sending campaigns is a separate operation.",
    ),
    (
        "emaillistverify",
        "official",
        "https://api.emaillistverify.com/api-doc",
        "Store an EmailListVerify API key, sent in x-api-key. GET /credits reads balances without verifying an email. POST /emailJobs accepts JSON email and optional quality; poll /emailJobs/JOB_ID for completion. Verification operations consume credits. Multipart list uploads and binary downloads are not supported by the generic JSON tool.",
    ),
    (
        "emailoctopus",
        "official",
        "https://emailoctopus.com/api-documentation/v2",
        "Store an EmailOctopus API key. Uses API v2 with Bearer authentication at https://api.emailoctopus.com, without a /v2 path prefix. GET /lists reads lists. Pass starting_after for cursor pagination. Legacy v1 query-key authentication is not used.",
    ),
    (
        "emailverify_io",
        "official",
        "https://www.emailverify.io/api/docs",
        "Store the account API key. Dotobot supplies key in GET queries and POST JSON bodies. GET /v2/check-account-balance reads credits; POST /v1/validate-batch accepts title and email_batch objects with address fields (maximum 5000). Poll /v1/get-result-bulk-verification-task/ with task_id. Verification consumes credits. Do not supply key in tool arguments.",
    ),
    (
        "emelia",
        "aggregator",
        "https://docs.emelia.io/docs/emelia/emelia",
        "Current REST API. Store the API key directly in Authorization without a Bearer prefix. GET /lists/list supports page and limit. New integrations should use Campaigns and Lists rather than legacy email-only endpoints. Campaign actions can initiate outreach; authenticated writes remain unverified.",
    ),
    (
        "encharge",
        "official",
        "https://docs.encharge.io/api-documentation",
        "REST API with an own-account API key from Account info, sent in X-Encharge-Token. GET /people/all accepts limit/offset; POST /tags takes tag and person identifiers. API writes may trigger flows. Shared partner OAuth setup and top-level array bodies for bulk people creation are not supported by this route. Ingest API uses a separate host.",
    ),
    (
        "endorsal",
        "official",
        "https://developers.endorsal.io/",
        "Official REST developer center. Generate a property-specific API key in Account > API. Requests use Authorization: Bearer; GET also accepts a key query parameter. Paths omit /v1. GET /tags lists tags; POST /tags accepts JSON name, type and description. Contact and AutoRequest operations may trigger outreach.",
    ),
    (
        "engage",
        "none",
        "https://docs.engage.so/en-us/a/62bbdd015bfea4dca4834041-api-overview",
        "Engage.so customer messaging. Store API_key:API_secret for Basic authentication. GET /lists; POST /lists accepts JSON title and optional description/double_optin. Customer changes can trigger messaging; use a test account.",
    ),
    (
        "enginemailer",
        "official",
        "https://enginemailer.zendesk.com/hc/en-us/articles/360003129972-Campaign-REST-API-GETTING-STARTED",
        "Store the profile API key; sent in APIKey. Campaign REST API requires a paid plan. Paths are relative to /restapi: GET /campaign/emcampaign/GetCategoryList; POST /Campaign/EMCampaign/CreateCampaign with a JSON object and verified SenderEmail domain. Inspect Result.Status and Result.StatusCode, not only HTTP status. Sending and scheduling campaigns are separate actions.",
    ),
    (
        "enormail",
        "official",
        "https://developer.enormail.eu/",
        "Store the Enormail API key alone. HTTP Basic uses it as username with an empty password. Paths are relative to /api/1.0, for example GET /account.json. Keep the .json endpoint suffix. POST and PUT bodies are form encoded, including bracket notation for nested fields. Pass body as an object. DELETE parameters belong in the path query string.",
    ),
    (
        "esputnik",
        "official",
        "https://docs.esputnik.com/reference/getting-started-with-your-api",
        "Store a secret in username:API_KEY format, using any nonempty username and the API key as the password. HTTP Basic authentication is used. Paths include their version, for example GET /v1/account/info. Most writes are asynchronous: an HTTP success means acceptance, not completed processing.",
    ),
    (
        "eventbrite",
        "official",
        "https://www.eventbrite.com/platform/new/api",
        "Store your Eventbrite personal OAuth token, not the application client secret. Authentication uses Bearer. Paths are relative to /v3 and normally end with a slash, for example GET /users/me/. JSON writes use the endpoint schema. Access depends on the token owner and organization permissions; OAuth authorization for other users is not performed by this stored-token route.",
    ),
    (
        "everwebinar",
        "official",
        "https://support.webinarjam.com/en/collections/19655442-everwebinar-api",
        "Store the approved account-wide API key. All documented operations use POST, including reads: /webinars with an empty body or /webinar with webinar_id and optional timezone. Dotobot adds api_key and form-encodes the body. Paths omit /everwebinar. Use API-returned schedule IDs for registrations, not dashboard IDs. Registration may send messages; obtain attendee consent. Inspect response status. API access requires provider approval; limit is 20 calls per second per user.",
    ),
    ("exact_mails", "none", "https://exactmails.com/", "No dedicated MCP."),
    (
        "ez_texting",
        "official",
        "https://mcp.eztexting.com/",
        "Dotobot uses mcp.eztexting.com/mcp.",
    ),
    (
        "facebook",
        "official",
        "https://www.postman.com/meta/messenger-platform-api",
        "Store the Meta access token appropriate to the endpoint: user token for /VERSION/me/accounts discovery, Page token for Page actions. Include a supported Graph API version in each path; no version is pinned by this connector. JSON writes are supported, including Messenger /VERSION/PAGE_ID/messages. App permissions and review apply. Avoid duplicating the token in tool arguments. OAuth consent/refresh, binary uploads and appsecret_proof generation are not automated.",
    ),
    (
        "feedblitz",
        "official",
        "https://developer.feedblitz.com/docs/rest-api/accessing-the-api/",
        "Store the REST API key. Dotobot adds key to the URL query and sends the required User-Agent. GET /user returns account XML. Paths omit /f.api. For XML writes pass body as an object with only an xml string containing the complete provider XML document. PUT creates; POST searches or updates. Responses remain XML text. Subscription operations can send activation emails and require provider verification. Separate Simple and Transactional APIs are not covered.",
    ),
    (
        "figma",
        "official",
        "https://developers.figma.com/docs/figma-mcp-server/",
        "Dev Mode MCP Server. Community alt: github.com/GLips/Figma-Context-MCP.",
    ),
    (
        "flexmail",
        "partial",
        "https://api.flexmail.eu/documentation/",
        "Store account_id:personal_access_token for Basic auth. This REST route covers contact management; campaign sending uses separate SOAP services and transactional email uses a separate host. GET /contacts; JSON writes use account resource IDs.",
    ),
    (
        "flippingbook",
        "official",
        "https://apidocs.flippingbook.com/",
        "Store a FlippingBook Online API key, sent as Bearer. GET /fbonline/publication lists publications with count and offset. POST the same path with JSON name and url for a reachable PDF; creation and conversion are separate, so inspect source status. Check success in responses. Access depends on your plan. This is the Online API, not desktop Publisher.",
    ),
    (
        "fomo",
        "official",
        "https://github.com/usefomo/fomo-python-sdk/blob/master/Fomo/fomo.py",
        "Store the site Auth Token from Settings > Site. Paths are relative to https://api.fomo.com/api/v1, for example /applications/me/events. Authentication uses Authorization: Token KEY. API access normally requires a paid plan.",
    ),
    (
        "freshmarketer",
        "official",
        "https://developer.freshmarketer.com/",
        "Configure the subdomain from your Freshmarketer account hostname. Store Settings > API Settings key; sent in fm-token. This documented standalone Freshmarketer API uses /mas/api/v1; paths omit that prefix. GET /contacts lists contacts. POST /email-types takes JSON name and description; PATCH /email-types/ID updates it. Freshworks CRM Suite hosts and authentication are separate and are not routed here. User roles limit access; subscription and campaign operations can contact people.",
    ),
    (
        "front",
        "official",
        "https://help.front.com/en/articles/4883136",
        "Dotobot uses mcp.frontapp.com/mcp.",
    ),
    (
        "frontify",
        "official",
        "https://www.frontify.com/en/blog/frontify-mcp",
        "Dotobot uses mcp.frontify-integrations.com/mcp.",
    ),
    (
        "fullenrich",
        "official",
        "https://fullenrich.com/mcp",
        "Dotobot uses mcp.fullenrich.com/mcp.",
    ),
    (
        "funnelcockpit",
        "official",
        "https://api.funnelcockpit.com/",
        "Store the private API key, sent directly in Authorization without Bearer. GET /me verifies the user; GET /email/tags uses zero-based page and limit. JSON bodies are supported, including POST /email/tag with contactId and tagId. Plan access applies; subscriber and tag operations can trigger automations.",
    ),
    (
        "getemails",
        "none",
        "https://docs.retention.com/docs/authentication",
        "GetEmails is now Retention.com. Store a JSON array [API ID, API key], sent in api-id and api-key headers. GET /validate checks credentials. File uploads and webhook delivery are not implemented by this JSON route.",
    ),
    (
        "getresponse",
        "official",
        "https://apidocs.getresponse.com/v3/authentication",
        "Store a GetResponse SMB API key. Uses https://api.getresponse.com/v3 and X-Auth-Token: api-key KEY. GET /accounts checks access. GetResponse MAX accounts require a different host and X-Domain and are not covered by this route.",
    ),
    (
        "getswift",
        "aggregator",
        "https://zapier.com/mcp/getswift",
        "No official vendor server.",
    ),
    (
        "giantcampaign",
        "official",
        "https://giantcampaign.com/developers/",
        "Store the GiantCampaign API token. Dotobot adds the required api_token query parameter from the secret store; do not include it in tool arguments. GET /lists or /campaigns reads resources. The documented POST endpoints also pass parameters in the URL query: supply those non-secret parameters in path, using URL encoding. JSON-body acceptance is not verified. Sending campaigns or subscriber actions may trigger email.",
    ),
    (
        "gist",
        "official",
        "https://developers.getgist.com/api/",
        "Store the Gist workspace API key from Integration Settings. Authentication uses Bearer. Paths are relative to https://api.getgist.com, for example GET /contacts. Writes use JSON. This is Gist customer messaging, not GitHub Gists or gist.ai.",
    ),
    (
        "github",
        "official",
        "https://github.com/settings/personal-access-tokens",
        "REST with a personal access token, not Copilot MCP. Classic: repo "
        "(private) or public_repo (public only). Fine-grained: Issues and "
        "Pull requests read/write on the repos bots should use. Optional org "
        "is the default owner for a bare repo name.",
    ),
    (
        "gitter",
        "none",
        "https://spec.matrix.org/latest/client-server-api/",
        "Gitter migrated to Matrix. Store a Matrix access token for its gitter.ems.host homeserver, not an old Gitter token. Paths omit /_matrix/client/v3. GET /account/whoami. Token lifecycle, sync loops and encrypted-room key management are not implemented. Current local DNS resolution of the advertised host failed; live access remains unverified.",
    ),
    (
        "gmail",
        "official",
        "https://developers.google.com/workspace/gmail/imap/xoauth2-protocol",
        "Connect your Google account to grant Gmail access. OAuth signs in to IMAP and SMTP and refreshes access automatically. Each inbox has its own connection. Bots search, read mail and attachments, draft, and send. App passwords are not supported.",
    ),
    (
        "gobio_link",
        "official",
        "https://gobio.link/api-documentation",
        "Bearer API key from account API settings. GET /user; multipart POST /projects. "
        "Scalar form fields supported; binary file uploads are not supported.",
    ),
    ("goodbits", "none", "https://goodbits.io/", "No known MCP server."),
    (
        "google_ad_manager",
        "community",
        "https://developers.google.com/ad-manager/api/beta/getting-started",
        "REST uses a stored OAuth access token. Enable the API and grant network access. End-user tokens require config quota_project; service-account tokens may omit it. Paths omit /v1. Token issuance and refresh are not automatic.",
    ),
    (
        "google_ads",
        "official",
        "https://developers.google.com/google-ads/api/docs/developer-toolkit/mcp-server",
        "Official MCP. REST credentials are a stored JSON array [OAuth access token, developer token]. Include the API version in paths. Optional config login_customer_id and linked_customer_id are digit-only IDs. Token creation and refresh are manual.",
    ),
    (
        "google_analytics",
        "official",
        "https://developers.google.com/analytics/devguides/reporting/data/v1/rest",
        "GA4 Data API. Store a current OAuth access token, not an API key or service-account JSON. Uses Bearer; consent, token creation and refresh are not implemented. Enable the Data API and grant the token identity property access with analytics.readonly or analytics scope. Include /v1beta or /v1alpha in paths. GET /v1beta/properties/PROPERTY_ID/metadata; POST /v1beta/properties/PROPERTY_ID:runReport with dimensions, metrics and dateRanges JSON. Set a small limit and page with offset to avoid response truncation. Admin API and Measurement Protocol use different hosts and are not routed here.",
    ),
    (
        "google_calendar",
        "official",
        "https://developers.google.com/workspace/calendar/api/v3/reference",
        "Connect your Google account to grant access. OAuth refreshes access automatically; pasted tokens are not supported. GET /users/me/calendarList lists calendars; use a token with calendar.calendarlist.readonly or another scope allowed by that endpoint. Writes need the corresponding calendar scope. Paths omit /calendar/v3.",
    ),
    (
        "google_drive",
        "official",
        "https://developers.google.com/workspace/drive/api/reference/rest/v3",
        "Connect your Google account to grant access. OAuth refreshes access automatically; pasted tokens are not supported. GET /files lists file metadata; drive.metadata.readonly is sufficient for that read. JSON metadata writes need an appropriate write scope. Paths omit /drive/v3. Binary and multipart uploads or downloads are not supported by these text tools.",
    ),
    (
        "google_sheets",
        "official",
        "https://developers.google.com/workspace/sheets/api/reference/rest/v4/spreadsheets/get",
        "Connect your Google account to grant access. OAuth refreshes access automatically; pasted tokens are not supported. GET /spreadsheets/SPREADSHEET_ID reads a spreadsheet; spreadsheets.readonly is sufficient for reads. Writes require spreadsheets or another supported write scope. Paths omit /v4. Use fields and ranges to limit large responses.",
    ),
    (
        "gosquared",
        "official",
        "https://www.gosquared.com/docs/configuration/",
        "Store the API Access key; Dotobot supplies api_key in the query string. Pass the project site_token as a query parameter when required; for POST include ?site_token=TOKEN in path. Include the API and version in paths: GET /now/v3/overview or /account/v1/sites; POST /tracking/v1/event takes JSON event and visitor_id or person_id. API key scopes apply. Use a separate test project for tracking because test data cannot be removed from realtime dashboards.",
    ),
    (
        "gozen_growth",
        "official",
        "https://docs.gozen.io/gozen-engage-knowledge-base/integration/gozen-growth",
        "Generate the Growth API key in account Settings > API key. Official integration "
        "guides confirm key-based access, but the REST host and header format remain unverified. "
        "GoZen Testimonials is a separate product and its API host must not be substituted.",
    ),
    (
        "grade_us",
        "official",
        "https://api.grade.us/",
        "Grade.us v4: raw API token in Authorization. JSON writes. "
        "GET /profiles lists profiles; recipient creation may initiate review outreach.",
    ),
    (
        "greenspark",
        "official",
        "https://docs.getgreenspark.com/reference/authentication",
        "Store a Greenspark API key, not a Widget key. Authentication uses X-API-KEY. Paths are relative to the production /v1 API, for example GET /projects. Impact writes take JSON and may incur charges. This route uses production; the separate demo and sandbox environments are not configured. Plan eligibility and key permissions apply.",
    ),
    (
        "growsurf",
        "official",
        "https://docs.growsurf.com/developer-tools/rest-api",
        "Store a GrowSurf API key. Paths are relative to https://api.growsurf.com/v2 and include the program ID, for example /campaign/PROGRAM_ID. Authentication uses Bearer; account plan eligibility is required.",
    ),
    (
        "handwrytten",
        "official",
        "https://mcp.handwrytten.com/",
        "Dotobot uses mcp.handwrytten.com/mcp.",
    ),
    (
        "herobot",
        "none",
        "https://help.herobot.ai/",
        "herobot.app redirects to herobot.ai; the current application is app.herobot.ai. "
        "Public help references API operations but does not establish the REST base or "
        "authentication format. Account-level API documentation is still required.",
    ),
    (
        "heyreach",
        "community",
        "https://github.com/bcharleson/heyreach-mcp",
        "Dotobot uses mcp.heyreach.io/mcp.",
    ),
    (
        "heysummit",
        "official",
        "https://app.heysummit.com/api/v2/docs/",
        "REST v2 uses Authorization: Token API_TOKEN. Get the token from Event Setup > "
        "API, MCP & Webhooks. GET /events/; JSON POST /events/ requires title. "
        "Preserve trailing slashes. Stored token excludes the Token prefix.",
    ),
    (
        "hippo_video",
        "official",
        "https://help.hippovideo.io/support/solutions/articles/19000095981-video-library-api",
        "Store an authentication_token, not the profile API key. GET /me/videos/list requires email and page in query and returns 20 videos per page; /me/video/VIDEO_ID reads details. Dotobot adds authentication_token to GET query or non-GET JSON body. Include email in the body for JSON personalization requests. Paths omit /api/v1. Token generation/refresh is not automatic: requesting another token revokes the previous one; default expiry is one month. File imports and bulk spreadsheet uploads are not verified by this route.",
    ),
    (
        "hubspot",
        "official",
        "https://developers.hubspot.com/mcp",
        "Official public beta. Dotobot uses mcp.hubspot.com/anthropic.",
    ),
    (
        "humanitix",
        "official",
        "https://api.humanitix.com/v1/documentation/json",
        "Store the public API key from Humanitix Account > Advanced. Authentication uses x-api-key. Production paths are relative to /v1, for example GET /events with query page=1, or /tags. The current API reference also lists bodyless POST /events/EVENT_ID/tickets/TICKET_ID/check-in and check-out. Event creation, event updates and ticket transfers require additional provider permission. Old console API keys do not work. Staging and optional location override headers are not configured.",
    ),
    (
        "hygraph",
        "official",
        "https://hygraph.com/docs/hygraph-ai/mcp-server",
        "Dotobot uses mcp.hygraph.com/mcp.",
    ),
    (
        "hypeauditor",
        "official",
        "https://hypeauditor.com/swagger/public-api/v1/",
        "Store the API token and configure numeric client_id. Sent as X-Auth-Hash and X-Auth-Id. GET /api/v1/media-plan/plans lists plans; POST the same path with JSON title creates one. Paths include their full API prefix. API access and credits are separate account entitlements. Report requests may consume credits; HTTP 202 requires waiting result.retryTtl before retrying.",
    ),
    (
        "hyperise",
        "official",
        "https://hyperise.customerly.help/en/collections/4317-api",
        "Store the Settings API token. Dotobot inserts api_token into the query; never pass it in tool arguments. GET /users/current verifies the account; GET /image-templates lists templates. POST /short-links uses form fields image_hash, url, title, desc and nested query_params. A custom link domain is required. Paths are relative to /api/v1/regular. Valid account and write acceptance remain unverified.",
    ),
    (
        "icontact",
        "official",
        "https://github.com/icontact/icontact-api-php",
        "Store a JSON array [appId, apiUsername, apiPassword] from the API integration, not your login password. Sends three credential headers and Api-Version 2.2. GET /a/ discovers accounts; GET /a/ACCOUNT/c/ discovers folders. Resource paths include /a/ACCOUNT/c/FOLDER. Writes accept JSON arrays as documented by the vendor SDK. This route targets standard iContact, not Pro or Pro Select.",
    ),
    (
        "impression",
        "none",
        "https://www.impressiondigital.com/",
        "No public API or MCP found.",
    ),
    (
        "indiefunnels",
        "none",
        "https://pipedream.com/apps/indiefunnels",
        "Generic Pipedream connector only.",
    ),
    (
        "infusionsoft",
        "official",
        "https://developer.infusionsoft.com/postman-quick-start/",
        "Infusionsoft is now Keap. Store a Personal Access Token or Service Account Key. Authentication uses X-Keap-API-Key. Paths are relative to /crm/rest/v1, for example GET /contacts; JSON bodies follow the REST v1 schema. This route does not use legacy XML-RPC keys or OAuth bearer tokens. REST v2 is not covered by this v1 base.",
    ),
    (
        "inksprout",
        "none",
        "https://inksprout.co/",
        "Current product is a video creation editor. The former /docs/index.html returns "
        "Cannot GET in the browser. A current API host, key format and schema remain unverified.",
    ),
    (
        "instabot",
        "official",
        "https://docs.instabot.io/docs/serverapi",
        'Store ["API_KEY", "MASTER_API_KEY"] as the secret JSON array. Uses X-Instabot-Api-Key and Authorization: X-Instabot-Master-Api-Key. GET /users?type=all lists anonymous and known users; POST /users/query?type=all searches using a JSON criteria object. Inspect apiStatusCode, apiStatusMessage and hasMoreRecords. User-session authentication and binary file transfers are not implemented.',
    ),
    (
        "instagram",
        "official",
        "https://www.postman.com/meta/instagram/documentation/6yqw8pt/instagram-api",
        "Store the appropriate OAuth access token. Config login_type defaults to instagram (graph.instagram.com); facebook selects graph.facebook.com for Facebook Login and its linked Page token. Include a supported API version in paths. Professional account and approved endpoint permissions are required. JSON messaging bodies and query-based media publishing requests are supported. Publish and messaging calls have external effects. OAuth refresh, binary uploads and appsecret_proof generation are not automated.",
    ),
    (
        "instantly",
        "official",
        "https://help.instantly.ai/en/articles/12980002-instantly-mcp-model-context-protocol",
        "Dotobot uses mcp.instantly.ai/mcp.",
    ),
    (
        "instasent",
        "official",
        "https://docs.instasent.com/developers/product-api/authentication/",
        "Store a scoped Product API token. Paths are relative to https://api.instasent.com/v1, for example /project/PROJECT_UID. Include the real project UID in resource paths. Authentication uses Bearer. This route covers the Product API, not the separate transactional SMS API.",
    ),
    (
        "intercom",
        "official",
        "https://developers.intercom.com/docs/guides/mcp",
        "Official. Also github.com/intercom/intercom-mcp-server.",
    ),
    (
        "jellyreach",
        "none",
        "https://developers.jellyreach.com/",
        "Store the API key directly in Authorization. GET /contacts; writes use URL-encoded form fields. Event data must be a JSON string in event_data. Contact updates and events may trigger messaging; account acceptance remains unverified.",
    ),
    (
        "jira",
        "official",
        "https://github.com/atlassian/atlassian-mcp-server",
        "Dotobot uses mcp.atlassian.com/v1/mcp (same server as Atlassian).",
    ),
    (
        "joggai",
        "official",
        "https://docs.jogg.ai/api-reference/v2/Webhook/ListWebhookEndpoints",
        "Store the JoggAI dashboard API key. Uses x-api-key with paths relative to /v2, for example GET /endpoints and POST /endpoint. Inspect the JSON code as well as HTTP status: only code 0 denotes success. JSON requests are supported; multipart uploads are not.",
    ),
    (
        "jvzoo",
        "official",
        "https://api.jvzoo.com/docs/",
        "Store the API Application key alone. Basic auth sends it as username with literal x as password. Include version in paths: GET /v3.0/transactions with start_date and end_date, or supported /v2.1 and /v2.0 paths. Writes accept JSON. Inspect meta.status and results. Payment cancellation and affiliate changes require care; do not retry mutations blindly.",
    ),
    (
        "kartra",
        "official",
        "https://support.kartra.com/en/articles/15369013-connecting-to-the-api",
        "Store a JSON object containing app_id, api_key and api_password. Use the request tool with POST, path /, and a body containing get_lead or documented actions. Credentials are injected into the form body. GET is unsupported even for reads. Check response status Error/Success. Create a custom app in My Apps; Test Mode suppresses lead email and replaces lead email domains. Live mode requires provider review.",
    ),
    (
        "kickofflabs",
        "official",
        "https://support.kickofflabs.com/developer/common-api-behavior/",
        "Store the campaign API Access key; uses Bearer with application/json. GET /campaigns lists campaigns. POST /CAMPAIGN_ID/ creates or updates a lead with email or phone_number. Bodies use JSON. Lead changes can trigger campaign automations. Rate limits and campaign permissions apply.",
    ),
    (
        "kingsumo",
        "none",
        "https://help.kingsumo.com/",
        "Provider team says API details are available in paid Lifetime account settings "
        "rather than public documentation. REST host and authentication remain unverified.",
    ),
    (
        "klaviyo",
        "official",
        "https://developers.klaviyo.com/en/docs/klaviyo_mcp_server",
        "Dotobot uses mcp.klaviyo.com/mcp.",
    ),
    (
        "klenty",
        "official",
        "https://support.klenty.com/en/articles/3197537-getting-started-with-klenty-api",
        "Store the API key from Klenty Settings > Integrations. Authentication uses x-API-key. Paths include the account email, URL-encoded as a path segment: GET /user/ACCOUNT_EMAIL/lists. POST /user/ACCOUNT_EMAIL/prospects accepts a JSON object with Email and FirstName. Inspect response status for operation success. This route supports individual JSON objects; bulk prospect arrays are not supported. Starting cadences can send outreach.",
    ),
    (
        "kyvio",
        "none",
        "https://kyvio.com/support",
        "The provider advertises API integrations, but its linked support portal currently shows a missing-page error. The Kyvio REST host/authentication contract still needs account or provider documentation. Mailvio is a separate product and is not substituted here.",
    ),
    (
        "lagrowthmachine",
        "official",
        "https://documenter.getpostman.com/view/32966764/2sBXqFM2Vv",
        "Store the API key from Settings > API; uses Bearer authentication. GET /members tests access. Paths are relative to /flow. Bodies use JSON except /audiences, /leads/status and /campaigns/ID/settings or status, which use form encoding. Pass body as an object. POST /audiences/create takes name. Campaign and inbox operations can trigger outreach.",
    ),
    (
        "lahar",
        "official",
        "https://www.postman.com/ramperpipeline/ramper-marketing-exemplo/documentation/byfyu4g/cadastro-atualizao-de-contato",
        "Lahar is now Ramper Marketing. Store the integration token; injected as token_api_lahar in JSON writes. The documented POST /conversions takes nome_formulario and email_contato and creates or updates a contact conversion. This can trigger marketing automation. The current example establishes this POST operation, not authenticated GET behavior.",
    ),
    (
        "laposta",
        "official",
        "https://api.laposta.nl/doc/index.en.php",
        "Store the Laposta API key alone; HTTP Basic uses it as the username with an empty password. Paths are relative to https://api.laposta.org/v2, for example GET /list. Regular writes use form fields with bracket notation for nested objects; POST /list/LIST_ID/members uses JSON for bulk synchronization. Pass the body as an object; Dotobot selects the encoding. Bulk synchronization requires a paid account.",
    ),
    (
        "lawmatics",
        "official",
        "https://help.lawmatics.com/en/articles/15939403-api-authentication-oauth2-setup-guide",
        "Store a Lawmatics OAuth access token obtained through a developer app. Authentication uses Bearer; paths are relative to /v1, for example GET /users/me. Lawmatics documents non-expiring tokens with no scopes and full account CRUD access; revoke through integration settings. This route does not perform OAuth consent. JSON bodies are supported, not multipart uploads.",
    ),
    (
        "lead_identity_check",
        "official",
        "https://leadidentitycheck.com/documentation/",
        "Store a JSON array [apiKey, filterKey] as the secret. Sends X-LIC-KEY and Filterkey headers. POST /main/lic/v1 accepts JSON Firstname, Lastname and Phone (all required), with optional Email and Address. Inspect Master Response and individual verification results; HTTP 200 alone is not a successful match. Requests may consume checks. No public read endpoint is documented; valid account acceptance remains unverified.",
    ),
    (
        "leaddyno",
        "official",
        "https://support.leaddyno.com/hc/en-us/articles/21508238902173-Getting-Started-with-LeadDyno-API-Tracking",
        "Store the LeadDyno private API key from Account > Profile, not the public tracking key. It is sent in the documented key header. GET /visitors reads visitor records. POST /visitors takes a url field; body objects are form-encoded. Lead and purchase writes can change affiliate attribution; use only test data when checking writes.",
    ),
    (
        "leadoku",
        "aggregator",
        "https://composio.dev/toolkits/leadoku/framework/claude-code",
        "Composio-hosted.",
    ),
    (
        "leadpops",
        "none",
        "https://leadpops.com/enterprise-mortgage-marketing",
        "The provider advertises API integrations and export, but the inspected public material does not publish a REST base, credential format or endpoint schema. Provider or account documentation is required before routing can be implemented.",
    ),
    (
        "linear",
        "official",
        "https://linear.app/docs/mcp",
        "Linear-hosted remote MCP. Dotobot uses mcp.linear.app/mcp.",
    ),
    (
        "linkedin",
        "official",
        "https://learn.microsoft.com/en-us/linkedin/marketing/community-management/shares/posts-api",
        "Store an OAuth access token, not an ID token. GET /v2/userinfo requires the OpenID Connect product and profile scope; email is optional. /rest/ requests include LinkedIn-Version 202609 and X-Restli-Protocol-Version 2.0.0. Config api_version may override with a supported YYYYMM release. POST /rest/posts requires approved social permissions and an author URN; publishing is a live external action. Token refresh and media uploads to other hosts are not automated.",
    ),
    (
        "mailchimp",
        "none",
        "https://mailchimp.com/developer/marketing/api/",
        "No confirmed well-known MCP; use Marketing API.",
    ),
    (
        "microsoft_excel",
        "official",
        "https://learn.microsoft.com/en-us/graph/api/workbook-list-worksheets?view=graph-rest-1.0",
        "Connect your Google account to grant access. OAuth refreshes access automatically; pasted tokens are not supported. GET /me/drive/items/ITEM_ID/workbook/worksheets lists worksheets. Use a delegated Graph token with Files.ReadWrite; application-only tokens are unsupported for this method. Calls are sessionless: workbook changes persist. Workbook-Session-Id and file uploads are not supported. Uses the global Graph cloud; paths omit /v1.0.",
    ),
    (
        "microsoft_outlook",
        "official",
        "https://learn.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0",
        "Connect your Google account to grant access. OAuth refreshes access automatically; pasted tokens are not supported. GET /me/messages lists messages with delegated Mail.ReadBasic for basic properties; bodies need Mail.Read. Application tokens use /users/USER_ID/messages with application permissions. Mail writes need corresponding permissions. Uses the global Graph cloud; paths omit /v1.0.",
    ),
    (
        "microsoft_teams",
        "official",
        "https://learn.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-1.0",
        "Connect your Google account to grant access. OAuth refreshes access automatically; pasted tokens are not supported. GET /me/joinedTeams requires delegated Team.ReadBasic.All with a work or school account. Personal accounts are unsupported. Application tokens use /users/USER_ID/joinedTeams. Other operations require their own permissions. Uses the global Graph cloud; paths omit /v1.0.",
    ),
    (
        "monday",
        "official",
        "https://developer.monday.com/apps/docs/mondaycom-mcp-integration",
        "Official. Open-source impl: github.com/mondaycom/monday-ai.",
    ),
    (
        "notion",
        "official",
        "https://developers.notion.com/docs/mcp",
        "Notion-hosted remote MCP via OAuth. Dotobot uses mcp.notion.com/mcp.",
    ),
    (
        "openai",
        "none",
        "https://platform.openai.com/docs/api-reference",
        "Primarily an MCP client/host, not a server. This is a provider, not a service MCP.",
    ),
    (
        "pipedrive",
        "aggregator",
        "https://composio.dev/toolkits/pipedrive",
        "Dotobot uses mcp.pipedrive.com/mcp.",
    ),
    (
        "quickbooks",
        "aggregator",
        "https://composio.dev/toolkits/quickbooks",
        "105 tools; no official Intuit-published MCP.",
    ),
    (
        "salesforce",
        "official",
        "https://github.com/salesforcecli/mcp",
        "Salesforce DX MCP Server (npm: @salesforce/mcp).",
    ),
    (
        "shopify",
        "official",
        "https://shopify.dev/docs/apps/build/storefront-mcp",
        "Storefront + Customer Accounts MCP. Dotobot uses https://{store_domain}/api/mcp.",
    ),
    (
        "slack",
        "community",
        "https://github.com/korotovsky/slack-mcp-server",
        "Table lists a community server; harness already uses official mcp.slack.com/mcp.",
    ),
    (
        "stripe",
        "official",
        "https://docs.stripe.com/mcp",
        "Official. Hosted at mcp.stripe.com.",
    ),
    (
        "telegram",
        "community",
        "https://github.com/sparfenyuk/mcp-telegram",
        "No official Telegram MCP.",
    ),
    (
        "trello",
        "official",
        "https://github.com/atlassian/trello-mcp-server",
        "Dotobot uses mcp.trello.com/v1.",
    ),
    (
        "twilio",
        "official",
        "https://github.com/twilio-labs/mcp",
        "Official. Docs: twilio.com/docs/ai/mcp.",
    ),
    (
        "typeform",
        "official",
        "https://www.typeform.com/developers/mcp/",
        "Dotobot uses api.typeform.com/mcp.",
    ),
    (
        "whatsapp",
        "none",
        "https://developers.facebook.com/docs/whatsapp/",
        "No official Meta MCP; unofficial community servers exist.",
    ),
    (
        "woocommerce",
        "official",
        "https://developer.woocommerce.com/docs/features/mcp/",
        "Official beta as of late 2025.",
    ),
    (
        "xero",
        "official",
        "https://github.com/XeroAPI/xero-mcp-server",
        "Dotobot uses mcp.xero.com/mcp.",
    ),
    (
        "zendesk",
        "none",
        "https://developer.zendesk.com/api-reference/",
        "No official vendor MCP; community + Zapier only.",
    ),
    (
        "zoom",
        "official",
        "https://developers.zoom.us/docs/mcp/",
        "Official. Dotobot uses mcp.zoom.us/mcp/meeting/streamable.",
    ),
    # Live catalog types that were not in the HeyMarcus table.
    (
        "ahrefs",
        "official",
        "https://docs.ahrefs.com/mcp/docs/introduction",
        "Official hosted MCP at api.ahrefs.com/mcp/mcp. Streamable HTTP + OAuth. Lite plan or higher.",
    ),
    (
        "granola",
        "official",
        "https://docs.granola.ai/help-center/sharing/integrations/mcp",
        "Official hosted MCP at mcp.granola.ai/mcp.",
    ),
    (
        "n8n",
        "official",
        "https://docs.n8n.io/advanced-ai/mcp/accessing-n8n-mcp-server/",
        "Instance MCP at https://{host}/mcp-server/http. OAuth or bearer token. Enable in Settings → Instance-level MCP.",
    ),
    (
        "triggerdev",
        "none",
        "https://trigger.dev/docs/mcp-introduction",
        "Official MCP is CLI stdio only (npx trigger.dev@latest mcp). No hosted HTTP URL.",
    ),
    (
        "1password",
        "none",
        "https://www.1password.dev/environments/mcp-server",
        "Official MCP is local stdio only (1password-mcp via the desktop app). No hosted HTTP URL. www.1password.dev/mcp is Mintlify docs search, not vaults.",
    ),
    (
        "google",
        "none",
        "https://developers.google.com/workspace",
        "Umbrella Google stub. Prefer the Gmail / Calendar / Drive / Sheets / Ads entries.",
    ),
    (
        "cloudflare",
        "official",
        "https://developers.cloudflare.com/agents/model-context-protocol/cloudflare/servers-for-cloudflare/",
        "Dotobot uses mcp.cloudflare.com/mcp (OAuth, or a pasted API token as bearer).",
    ),
    (
        "paypal",
        "official",
        "https://developer.paypal.com/",
        "Dotobot uses mcp.paypal.com/mcp.",
    ),
    (
        "square",
        "official",
        "https://developer.squareup.com/",
        "Dotobot uses mcp.squareup.com/mcp.",
    ),
    (
        "sentry",
        "official",
        "https://docs.sentry.io/",
        "Dotobot uses mcp.sentry.dev/mcp.",
    ),
    (
        "vercel",
        "official",
        "https://vercel.com/docs",
        "Dotobot uses mcp.vercel.com.",
    ),
    (
        "posthog",
        "official",
        "https://posthog.com/docs",
        "Dotobot uses mcp.posthog.com/mcp.",
    ),
    (
        "amplitude",
        "official",
        "https://amplitude.com/docs",
        "Dotobot uses mcp.amplitude.com/mcp.",
    ),
    (
        "miro",
        "official",
        "https://developers.miro.com/",
        "Dotobot uses mcp.miro.com/.",
    ),
    (
        "canva",
        "official",
        "https://www.canva.dev/docs/connect/",
        "Dotobot uses mcp.canva.com/mcp.",
    ),
    (
        "webflow",
        "official",
        "https://developers.webflow.com/mcp/reference/overview",
        "Dotobot uses mcp.webflow.com/mcp.",
    ),
    (
        "zapier",
        "official",
        "https://zapier.com/mcp",
        "Dotobot uses mcp.zapier.com/api/v1/connect.",
    ),
    (
        "composio",
        "official",
        "https://docs.composio.dev/docs/composio-connect",
        "Official hosted MCP at connect.composio.dev/mcp. Streamable HTTP + OAuth. Seven meta-tools over 1000+ apps.",
    ),
    (
        "atlassian",
        "official",
        "https://github.com/atlassian/atlassian-mcp-server",
        "Rovo MCP. Dotobot uses mcp.atlassian.com/v1/mcp. Jira is also a separate gallery stub.",
    ),
]

DOCS: dict[str, dict[str, str]] = {}
for _type, _publisher, _docs, _notes in _ROWS:
    if _type in DOCS:
        raise ValueError(f"duplicate connector_docs type {_type}")
    DOCS[_type] = {"publisher": _publisher, "docs": _docs, "notes": _notes}
