"""Setup notes for each catalog connector: docs URL, MCP publisher, comments.

Merged onto catalog() rows as `docs` / `publisher` / `notes`. Publisher is
`official`, `community`, `aggregator`, `partial`, or `none`. Aggregator means
Zapier / Composio / Pipedream — not a first-party MCP URL we can OAuth to.
"""

from __future__ import annotations

# type, publisher, docs URL, notes
_ROWS: list[tuple[str, str, str, str]] = [
    (
        "360nrs",
        "official",
        "https://apidocs.360nrs.com/",
        "Store username:apiPassword as the secret, using the API password, not the platform login password. Allow the server IP in 360NRS settings. Paths are relative to https://dashboard.360nrs.com/api/rest; HTTP Basic authentication is used.",
    ),
    (
        "4dem",
        "official",
        "https://api.4dem.it/open-api",
        "Store the 4Dem API key. The connector exchanges it at /authenticate for a bearer token before every request. Paths are relative to https://api.4dem.it, for example /addressbook/. Dedicated and partner API-channel hosts are not covered.",
    ),
    (
        "abyssale",
        "official",
        "https://developers.abyssale.com/rest-api/quickstart",
        "Store a workspace API key. REST paths are relative to https://api.abyssale.com; for example GET /designs. Authentication uses x-api-key.",
    ),
    (
        "acelle_mail",
        "official",
        "https://acellesend.com/rest-api",
        "Set instance_domain to the HTTPS hostname of your Acelle Mail installation, without a scheme or path. Store the API token from My Profile > API and Authentication. Paths are relative to /api/v1, for example /me. Authentication uses Bearer. Installations under a URL subdirectory are not covered.",
    ),
    (
        "activecampaign",
        "official",
        "https://developers.activecampaign.com/reference/authentication",
        "Set api_domain to the host from Settings > Developer API URL, without https:// or /api/3. Do not guess the region. Store the API token. Paths are relative to /api/3, for example /users/me; authentication uses Api-Token.",
    ),
    (
        "active_trail",
        "official",
        "https://webapi.mymarketing.co.il/api/docs/Guides",
        "Store the access token from Settings > API apps. The token is sent unchanged in Authorization. Paths are relative to https://webapi.mymarketing.co.il/api, for example /groups. Check token expiry and allowed IPs.",
    ),
    (
        "acumbamail",
        "community",
        "https://github.com/ever-works/awesome-mcp-servers/blob/master/details/acumbamail-mcp-server.md",
        "Listed in awesome-mcp-servers.",
    ),
    (
        "acymailing",
        "aggregator",
        "https://mcp.pipedream.com/app/acymailing",
        "Pipedream-generated actions.",
    ),
    (
        "add_to_calendar_pro",
        "none",
        "https://add-to-calendar-pro.com/",
        "WP/JS plugin. No MCP.",
    ),
    ("adhook", "none", "", "No public docs surfaced."),
    (
        "adrapid",
        "aggregator",
        "https://mcp.pipedream.com/app/adrapid",
        "Pipedream-hosted.",
    ),
    (
        "adroll",
        "official",
        "https://help.adroll.com/hc/en-us/articles/44128588376077-AdRoll-MCP-Server-Beta",
        "Official MCP beta (2026).",
    ),
    (
        "adtraction",
        "aggregator",
        "https://zapier.com/mcp/adtraction",
        "Affiliate network via Zapier MCP.",
    ),
    (
        "aimtell",
        "none",
        "https://developers.aimtell.com/reference/api-send-push-notification",
        "Push notification REST API. No MCP.",
    ),
    (
        "airship",
        "official",
        "https://www.airship.com/docs/developer/ai-tools/mcp-server/",
        "Official MCP. Also github.com/urbanairship/agent-tools.",
    ),
    (
        "airtable",
        "official",
        "https://support.airtable.com/articles/9897799762-using-the-airtable-mcp-server",
        "Official MCP. Popular alt: github.com/domdomegg/airtable-mcp-server.",
    ),
    (
        "amazon_advertising",
        "official",
        "https://advertising.amazon.com/library/news/amazon-ads-mcp-server-open-beta",
        "Dotobot uses advertising-ai.amazon.com/mcp.",
    ),
    (
        "anthropic",
        "none",
        "https://github.com/modelcontextprotocol/servers",
        "Anthropic authored the MCP spec and reference servers; this is a provider, not a service MCP.",
    ),
    (
        "apexverify",
        "aggregator",
        "https://composio.dev/toolkits/apexverify",
        "Composio-hosted.",
    ),
    (
        "appsflyer",
        "none",
        "https://dev.appsflyer.com/",
        "AppsFlyer API docs. No MCP in the research table.",
    ),
    (
        "arpoone",
        "none",
        "https://docs.arpoone.com/api-reference/",
        "General API reference. No MCP.",
    ),
    (
        "asana",
        "official",
        "https://developers.asana.com/docs/mcp-server",
        "Vendor-hosted remote MCP.",
    ),
    ("asters", "none", "", "Niche/unclear vendor. No public docs."),
    (
        "attentive",
        "official",
        "https://docs.attentive.com/docs/authentication",
        "Store the private application API key. Paths are relative to https://api.attentivemobile.com/v1; GET /subscriptions needs an email or phone query. Authentication uses Bearer.",
    ),
    ("autoklose", "none", "https://autoklose.com/", "No MCP found."),
    (
        "automizy",
        "none",
        "https://www.getresponse.com/",
        "Discontinued / absorbed into GetResponse.",
    ),
    (
        "aweber",
        "official",
        "https://docs.aweber.com/integrations/integrations/aweber-mcp-integration-ai-powered-email-marketing-management",
        "Dotobot uses mcp.aweber.com/mcp.",
    ),
    (
        "beamer",
        "official",
        "https://www.getbeamer.com/help/how-to-use-single-user-notifications",
        "Store a Beamer API key from Settings > API. Paths are relative to /v0, for example GET /posts or POST /posts with a JSON body. Authentication uses Beamer-Api-Key. Key permissions control read and write access.",
    ),
    (
        "beehiiv",
        "official",
        "https://www.beehiiv.com/features/mcp",
        "Dotobot uses mcp.beehiiv.com/mcp.",
    ),
    (
        "benchmark_email",
        "aggregator",
        "https://composio.dev/toolkits/benchmark_email",
        "Composio; also Zapier/Pipedream.",
    ),
    (
        "bigmailer",
        "official",
        "https://docs.bigmailer.io/docs/getting-started-api",
        "Store a BigMailer API key. Paths are relative to https://api.bigmailer.io/v1, for example /me. Authentication uses X-API-Key and JSON bodies.",
    ),
    (
        "bitly",
        "official",
        "https://dev.bitly.com/bitly-mcp/overview/what-is-mcp",
        "Dotobot uses api-ssl.bitly.com/v4/mcp.",
    ),
    (
        "botconversa",
        "aggregator",
        "https://mcp.pipedream.com/app/botconversa",
        "Pipedream-generated.",
    ),
    (
        "brandfetch",
        "official",
        "https://docs.brandfetch.com/mcp/overview",
        "Dotobot uses mcp.brandfetch.io/mcp.",
    ),
    ("brandmentions", "none", "https://brandmentions.com/", "No MCP found."),
    (
        "braze",
        "official",
        "https://www.braze.com/docs/user_guide/brazeai/mcp_server",
        "Dotobot uses mcp.braze.com/mcp.",
    ),
    (
        "builderall_mailingboss",
        "aggregator",
        "https://viasocket.com/mcp/builderall-mailingboss",
        "Third-party viaSocket connector.",
    ),
    ("buysellads", "none", "https://docs.buysellads.com/", "No MCP found."),
    (
        "calendly",
        "official",
        "https://developer.calendly.com/calendly-mcp-server",
        "Dotobot uses mcp.calendly.com.",
    ),
    (
        "callpage",
        "aggregator",
        "https://composio.dev/toolkits/callpage",
        "Composio-generated.",
    ),
    (
        "callrail",
        "official",
        "https://apidocs.callrail.com/",
        "Store a CallRail API key. Paths are relative to https://api.callrail.com/v3, for example GET /a.json. Authentication uses Authorization: Token token=KEY.",
    ),
    (
        "campaign_cleaner",
        "official",
        "https://docs.campaigncleaner.com/api-reference/endpoint/get-credits",
        "Store a Campaign Cleaner API key. Authentication uses X-CC-API-Key. GET /get_credits reads the credit balance. POST /send_campaign accepts a send_campaign object with campaign_html and campaign_name; this submits analysis and consumes credits. Poll the campaign status before retrieving results. JSON endpoints are supported; binary PDF responses are not.",
    ),
    (
        "campaign_monitor",
        "official",
        "https://www.campaignmonitor.com/api/v3-3/getting-started/",
        "Store only the Campaign Monitor API key. HTTP Basic uses it as username with an empty password. Paths are relative to https://api.createsend.com/api/v3.3; use .json endpoints such as /clients.json.",
    ),
    (
        "campaignhq",
        "none",
        "https://campaignhq.docs.apiary.io/",
        "Official Ruby API client, no MCP.",
    ),
    (
        "campayn",
        "official",
        "https://github.com/nebojsac/Campayn-API",
        "Store an API key from the Campayn Account section. Authentication uses Authorization: TRUEREST apikey=KEY. GET /lists.json reads lists. JSON writes such as POST /lists/LIST_ID/contacts.json add contacts; inspect success in the response. Keep the .json endpoint suffix.",
    ),
    (
        "cardly",
        "official",
        "https://api.card.ly/v2/docs",
        "Store a Cardly test_ or live_ API key; use test_ keys to avoid order mutations while testing. Paths are relative to https://api.card.ly/v2, for example /art. Authentication uses API-Key and bodies use text/json as required by Cardly.",
    ),
    ("catch_all_verifier", "none", "https://catchallverifier.com/", "No docs found."),
    (
        "chatrace",
        "none",
        "https://chatrace.com/",
        "Only automation listings, no genuine MCP.",
    ),
    (
        "cleverreach",
        "official",
        "https://developers.cleverreach.com/docs/api-categories/introduction/",
        "Store a current CleverReach OAuth access token, not the client secret. Authentication uses Bearer. Paths are relative to /v3, for example GET /groups or POST /groups with a JSON name field. OAuth consent and expired-token refresh are not performed by this stored-token route.",
    ),
    (
        "clevertap",
        "community",
        "https://github.com/ralphcorleone/clevertap-mcp",
        "Also Zapier/Pipedream.",
    ),
    (
        "clickfunnels",
        "official",
        "https://support.myclickfunnels.com/docs/clickfunnels-mcp-server-beta-1",
        "Vendor MCP beta.",
    ),
    (
        "clickup",
        "official",
        "https://developer.clickup.com/docs/connect-an-ai-assistant-to-clickups-mcp-server",
        "Dotobot uses mcp.clickup.com/mcp.",
    ),
    (
        "cloud_convert",
        "official",
        "https://cloudconvert.com/docs/getting-started/introduction",
        "Store a scoped CloudConvert API key. Uses the production https://api.cloudconvert.com/v2 API; GET /users/me requires user.read. Paths omit /v2. Authentication uses Bearer.",
    ),
    (
        "cometly",
        "official",
        "https://docs.cometly.com/introduction/authentication",
        "Store the Cometly API integration key. Authentication uses Bearer; Accept and Content-Type are application/json, including GET requests. Paths are relative to /public-api/v1. GET /events requires start_date and end_date in YYYY-MM-DD HH:MM:SS format in the space timezone. This is the REST API, not the separate MCP endpoint.",
    ),
    (
        "constant_contact",
        "official",
        "https://developer.constantcontact.com/api_guide/getting-started/v3-technical-overview",
        "Store a current Constant Contact V3 OAuth access token. Authentication uses Bearer; paths are relative to /v3, for example GET /contacts. Writes use JSON and require corresponding scopes. OAuth consent and expired-token refresh are not performed by this stored-token route.",
    ),
    (
        "contentdrips",
        "none",
        "https://developer.contentdrips.com/",
        "No dedicated MCP.",
    ),
    (
        "contentful",
        "official",
        "https://www.contentful.com/developers/docs/tools/mcp-server/",
        "Dotobot uses mcp.contentful.com/mcp.",
    ),
    (
        "convertkit",
        "official",
        "https://developers.kit.com/api-reference/authentication",
        "ConvertKit is now Kit. Store a V4 API key from Developer settings for personal account automation. Authentication uses X-Kit-Api-Key; paths are relative to /v4, for example GET /account. Legacy V3 keys are incompatible. Some endpoints, including bulk and purchase creation, require OAuth and are not covered by this key route.",
    ),
    (
        "copicake",
        "official",
        "https://docs.copicake.com/api/v1-image-get",
        "Store a Copicake API key. Paths are relative to /v1. GET /image/get requires the rendering id query parameter. POST /image/create accepts template_id, changes and options as JSON. Authentication uses Bearer.",
    ),
    (
        "coupontools",
        "none",
        "https://docs.coupontools.com/",
        "REST API, no MCP.",
    ),
    (
        "crowdpower",
        "official",
        "https://docs.crowdpower.io/getting-started/beacon-api",
        "Store a CrowdPower project secret or application key. Authentication uses Bearer. Uses the Beacon ingestion API, for example POST /customers with user_id and customer fields as JSON, or /customers/bulk with a customers array. This scope provides ingestion, not a documented customer-list GET. Inspect the response success and code fields. Ingestion can trigger configured marketing automations.",
    ),
    (
        "cufinder",
        "official",
        "https://apidoc.cufinder.io/mcp/introduction",
        "Dotobot uses mcp.cufinder.io/mcp.",
    ),
    (
        "curated",
        "aggregator",
        "https://composio.dev/toolkits/curated",
        "Composio auto-generated.",
    ),
    (
        "customer_io",
        "official",
        "https://docs.customer.io/ai/mcp/get-started/",
        "Dotobot uses mcp.customer.io/mcp.",
    ),
    (
        "cyberimpact",
        "official",
        "https://api.cyberimpact.com/docs",
        "Store the JWT API token from Developers > API tokens. Authentication uses Bearer. Paths are relative to https://api.cyberimpact.com; GET /groups reads groups and POST /groups accepts JSON with title and isPublic. Use page and limit for pagination.",
    ),
    (
        "demandbase",
        "official",
        "https://developer.demandbase.com/docs/mcp",
        "Vendor docs.",
    ),
    (
        "demio",
        "aggregator",
        "https://composio.dev/toolkits/demio",
        "Composio toolkit.",
    ),
    (
        "discourse",
        "official",
        "https://github.com/discourse/discourse-mcp",
        "Official. Announced Oct 2025.",
    ),
    (
        "docupost",
        "aggregator",
        "https://composio.dev/toolkits/docupost",
        "Composio toolkit.",
    ),
    (
        "doppler",
        "official",
        "https://restapi.fromdoppler.com/docs/gettingstarted",
        "Store a Doppler Email Marketing API key from Control Panel > Advanced Preferences. Paths are relative to https://restapi.fromdoppler.com, for example /accounts/ACCOUNT_EMAIL/lists. Authentication uses token KEY. This is not the Doppler secrets product.",
    ),
    (
        "dribbble",
        "aggregator",
        "https://zapier.com/mcp/dribbble",
        "Also unofficial Apify scrapers.",
    ),
    (
        "drip",
        "official",
        "https://developer.drip.com/",
        "Store the personal API token. HTTP Basic uses it as username with an empty password. Paths are relative to https://api.getdrip.com and include their version, for example /v2/accounts or /v3/ACCOUNT_ID/shopper_activity/order/batch.",
    ),
    (
        "dripcel",
        "aggregator",
        "https://docs.composio.dev/toolkits/dripcel",
        "Composio toolkit.",
    ),
    (
        "dropbox",
        "official",
        "https://help.dropbox.com/integrations/connect-dropbox-mcp-server",
        "Dotobot uses mcp.dropbox.com/mcp.",
    ),
    (
        "dropcontact",
        "official",
        "https://developer.dropcontact.com/",
        "Store a Dropcontact access token. Paths are relative to https://api.dropcontact.com/v1/enrich; use /all for enrichment and /webhook for callback configuration. Authentication uses X-Access-Token.",
    ),
    (
        "dub",
        "official",
        "https://dub.co/docs/mcp-server",
        "Dotobot uses mcp.dub.sh/mcp/dub-partners.",
    ),
    (
        "dux_soup",
        "official",
        "https://www.dux-soup.com/blog/dux-soup-mcp-use-ai-to-control-your-linkedin-automation",
        "Official + aggregator. Also zapier.com/mcp/dux-soup.",
    ),
    (
        "dynamic_content_snippet",
        "none",
        "",
        "Likely a feature name, not a standalone vendor.",
    ),
    (
        "dynapictures",
        "official",
        "https://dynapictures.com/docs/",
        "Store a DynaPictures API key. Paths are relative to https://api.dynapictures.com, for example /workspaces or /designs/TEMPLATE_ID. Authentication uses Bearer.",
    ),
    (
        "egoi",
        "official",
        "https://developers.e-goi.com/api/v3/",
        "Store the E-goi API key from account settings. Paths are relative to https://api.egoiapp.com, for example /my-account; do not add /v3. Authentication uses Apikey.",
    ),
    (
        "easypromos",
        "none",
        "https://developers.easypromosapp.com/",
        "General API docs. No MCP.",
    ),
    (
        "easysendy",
        "aggregator",
        "https://zapier.com/mcp/easysendy-pro-da35212",
        "No official vendor MCP.",
    ),
    (
        "echtpost_postcards",
        "aggregator",
        "https://mcp.composio.dev/echtpost",
        "Composio toolkit.",
    ),
    (
        "ecologi",
        "official",
        "https://docs.ecologi.com/",
        "Store the Ecologi Impact API key; authentication uses Bearer. Paths are relative to https://public.ecologi.com. POST /impact/trees takes a JSON number and test flag. Set test to true for non-billable test requests; live impact purchases are billed. Public reporting uses GET /users/USERNAME/trees and does not require authentication at the provider, although this connector currently requires a stored key. Idempotency-Key headers are not exposed; do not automatically retry purchase requests.",
    ),
    (
        "elastic_email",
        "official",
        "https://github.com/ElasticEmail/elasticemail-mcp-server",
        "Dotobot uses mcp.elasticemail.com/mcp.",
    ),
    (
        "email_on_acid",
        "official",
        "https://api.emailonacid.com/docs/latest",
        "Store api_key:account_password as the secret for HTTP Basic authentication. Paths are relative to https://api.emailonacid.com/v5, for example /auth. The documented public sandbox uses sandbox:sandbox.",
    ),
    (
        "emailable",
        "official",
        "https://emailable.com/docs/api/authentication/",
        "Store an Emailable private API key or OAuth access token. Paths are relative to https://api.emailable.com/v1, for example /account. Authentication uses Bearer; public keys only allow verification. Test keys simulate verification without using credits.",
    ),
    ("emailchef", "none", "https://www.emailchef.com/", "No dedicated MCP."),
    (
        "emaillistverify",
        "official",
        "https://emaillistverify.com/mcp-server",
        "Vendor MCP. Also on Pipedream/Composio.",
    ),
    (
        "emailoctopus",
        "official",
        "https://emailoctopus.com/api-documentation/v2",
        "Store an EmailOctopus API key. Uses API v2 with Bearer authentication at https://api.emailoctopus.com, without a /v2 path prefix. GET /lists reads lists. Pass starting_after for cursor pagination. Legacy v1 query-key authentication is not used.",
    ),
    (
        "emailverify_io",
        "official",
        "https://www.emailverify.io/mcp/",
        "Vendor-published MCP.",
    ),
    (
        "emelia",
        "aggregator",
        "https://composio.dev/toolkits/emelia",
        "Composio toolkit only.",
    ),
    (
        "encharge",
        "aggregator",
        "https://zapier.com/mcp/encharge",
        "Zapier/viaSocket only.",
    ),
    ("endorsal", "none", "https://endorsal.io/", "No MCP found."),
    ("engage", "none", "", "Too generic to identify a specific vendor."),
    (
        "enginemailer",
        "community",
        "https://www.npmjs.com/package/@lightyoruichi/enginemailer-mcp",
        "Third-party npm package.",
    ),
    (
        "enormail",
        "official",
        "https://developer.enormail.eu/",
        "Store the Enormail API key alone. HTTP Basic uses it as username with an empty password. Paths are relative to /api/1.0, for example GET /account.json. Keep the .json endpoint suffix. POST and PUT bodies are form encoded, including bracket notation for nested fields. Pass body as an object. DELETE parameters belong in the path query string.",
    ),
    (
        "esputnik",
        "official",
        "https://docs.esputnik.com/reference/getting-started-with-your-api",
        "Store a secret in username:API_KEY format, using any nonempty username and the API key as the password. HTTP Basic authentication is used. Paths include their version, for example GET /v1/account/info. Most writes are asynchronous: an HTTP success means acceptance, not completed processing.",
    ),
    (
        "eventbrite",
        "official",
        "https://www.eventbrite.com/platform/new/api",
        "Store your Eventbrite personal OAuth token, not the application client secret. Authentication uses Bearer. Paths are relative to /v3 and normally end with a slash, for example GET /users/me/. JSON writes use the endpoint schema. Access depends on the token owner and organization permissions; OAuth authorization for other users is not performed by this stored-token route.",
    ),
    (
        "everwebinar",
        "aggregator",
        "https://zapier.com/mcp/webinarjam",
        "Listed jointly with WebinarJam.",
    ),
    ("exact_mails", "none", "https://exactmails.com/", "No dedicated MCP."),
    (
        "ez_texting",
        "official",
        "https://mcp.eztexting.com/",
        "Dotobot uses mcp.eztexting.com/mcp.",
    ),
    (
        "facebook",
        "aggregator",
        "https://zapier.com/mcp/facebook-pages",
        "Also community repos; no official Meta server.",
    ),
    (
        "feedblitz",
        "none",
        "https://developer.feedblitz.com/",
        "REST API, no MCP.",
    ),
    (
        "figma",
        "official",
        "https://developers.figma.com/docs/figma-mcp-server/",
        "Dev Mode MCP Server. Community alt: github.com/GLips/Figma-Context-MCP.",
    ),
    (
        "flexmail",
        "partial",
        "https://www.mcpbundles.com/skills/flexmail",
        "Fallback API docs: developer.flexmail.eu.",
    ),
    (
        "flippingbook",
        "none",
        "https://flippingbook.com/help/publisher-2",
        "No MCP found.",
    ),
    (
        "fomo",
        "official",
        "https://github.com/usefomo/fomo-python-sdk/blob/master/Fomo/fomo.py",
        "Store the site Auth Token from Settings > Site. Paths are relative to https://api.fomo.com/api/v1, for example /applications/me/events. Authentication uses Authorization: Token KEY. API access normally requires a paid plan.",
    ),
    (
        "freshmarketer",
        "partial",
        "https://developers.freshworks.com/docs/agentic-dev-tools/mcp-server/",
        "Freshworks MCP gateway covers Freshmarketer.",
    ),
    (
        "front",
        "official",
        "https://help.front.com/en/articles/4883136",
        "Dotobot uses mcp.frontapp.com/mcp.",
    ),
    (
        "frontify",
        "official",
        "https://www.frontify.com/en/blog/frontify-mcp",
        "Dotobot uses mcp.frontify-integrations.com/mcp.",
    ),
    (
        "fullenrich",
        "official",
        "https://fullenrich.com/mcp",
        "Dotobot uses mcp.fullenrich.com/mcp.",
    ),
    (
        "funnelcockpit",
        "aggregator",
        "https://zapier.com/mcp/funnelcockpit",
        "No vendor-native server.",
    ),
    ("getemails", "none", "https://getemails.com/", "No dedicated MCP found."),
    (
        "getresponse",
        "official",
        "https://apidocs.getresponse.com/v3/authentication",
        "Store a GetResponse SMB API key. Uses https://api.getresponse.com/v3 and X-Auth-Token: api-key KEY. GET /accounts checks access. GetResponse MAX accounts require a different host and X-Domain and are not covered by this route.",
    ),
    (
        "getswift",
        "aggregator",
        "https://zapier.com/mcp/getswift",
        "No official vendor server.",
    ),
    ("giantcampaign", "none", "https://www.giantcampaign.com/", "No known MCP server."),
    (
        "gist",
        "official",
        "https://developers.getgist.com/api/",
        "Store the Gist workspace API key from Integration Settings. Authentication uses Bearer. Paths are relative to https://api.getgist.com, for example GET /contacts. Writes use JSON. This is Gist customer messaging, not GitHub Gists or gist.ai.",
    ),
    (
        "github",
        "official",
        "https://github.com/settings/personal-access-tokens",
        "REST with a personal access token, not Copilot MCP. Classic: repo "
        "(private) or public_repo (public only). Fine-grained: Issues and "
        "Pull requests read/write on the repos bots should use. Optional org "
        "is the default owner for a bare repo name.",
    ),
    (
        "gitter",
        "none",
        "https://developer.gitter.im/docs/",
        "Largely legacy / merged into Matrix/Element.",
    ),
    (
        "gmail",
        "official",
        "https://myaccount.google.com/apppasswords",
        "Signs in with a Google app password over IMAP and SMTP — no Google Cloud project, OAuth client, or consent screen. 1. Turn on 2-Step Verification for the Google account (Google Account → Security). 2. Open the app passwords page (link below), enter a name such as Harness, and tap Create. 3. Paste the Gmail address and the 16-character password shown here. Bots search and read mail and attachments (PDF text extraction included), draft, and send. Each inbox is its own account: Add another account for a second address.",
    ),
    ("gobio_link", "none", "https://gobio.link/", "No known MCP or public API docs."),
    ("goodbits", "none", "https://goodbits.io/", "No known MCP server."),
    (
        "google_ad_manager",
        "community",
        "https://github.com/MatiousCorp/google-ad-manager-mcp",
        "No official Google-published GAM MCP.",
    ),
    (
        "google_ads",
        "official",
        "https://developers.google.com/google-ads/api/docs/developer-toolkit/mcp-server",
        "Official. Announced Oct 2025.",
    ),
    (
        "google_analytics",
        "official",
        "https://developers.google.com/analytics/devguides/MCP",
        "Official GA4 MCP server.",
    ),
    (
        "google_calendar",
        "official",
        "https://developers.google.com/workspace/calendar/api/v3/reference",
        "Store a current OAuth access token as the connector secret, not an API key, refresh token or client secret. Authentication uses Bearer. This route does not run OAuth consent or refresh expired tokens; replace the stored access token when it expires. GET /users/me/calendarList lists calendars; use a token with calendar.calendarlist.readonly or another scope allowed by that endpoint. Writes need the corresponding calendar scope. Paths omit /calendar/v3.",
    ),
    (
        "google_drive",
        "official",
        "https://developers.google.com/workspace/drive/api/reference/rest/v3",
        "Store a current OAuth access token as the connector secret, not an API key, refresh token or client secret. Authentication uses Bearer. This route does not run OAuth consent or refresh expired tokens; replace the stored access token when it expires. GET /files lists file metadata; drive.metadata.readonly is sufficient for that read. JSON metadata writes need an appropriate write scope. Paths omit /drive/v3. Binary and multipart uploads or downloads are not supported by these text tools.",
    ),
    (
        "google_sheets",
        "official",
        "https://developers.google.com/workspace/sheets/api/reference/rest/v4/spreadsheets/get",
        "Store a current OAuth access token as the connector secret, not an API key, refresh token or client secret. Authentication uses Bearer. This route does not run OAuth consent or refresh expired tokens; replace the stored access token when it expires. GET /spreadsheets/SPREADSHEET_ID reads a spreadsheet; spreadsheets.readonly is sufficient for reads. Writes require spreadsheets or another supported write scope. Paths omit /v4. Use fields and ranges to limit large responses.",
    ),
    (
        "gosquared",
        "aggregator",
        "https://composio.dev/toolkits/gosquared",
        "No dedicated vendor server.",
    ),
    (
        "gozen_growth",
        "aggregator",
        "https://zapier.com/mcp/gozen-growth",
        "Also Composio toolkit.",
    ),
    ("grade_us", "none", "https://gradeus.com/", "No public docs surfaced."),
    (
        "greenspark",
        "official",
        "https://docs.getgreenspark.com/reference/authentication",
        "Store a Greenspark API key, not a Widget key. Authentication uses X-API-KEY. Paths are relative to the production /v1 API, for example GET /projects. Impact writes take JSON and may incur charges. This route uses production; the separate demo and sandbox environments are not configured. Plan eligibility and key permissions apply.",
    ),
    (
        "growsurf",
        "official",
        "https://docs.growsurf.com/developer-tools/rest-api",
        "Store a GrowSurf API key. Paths are relative to https://api.growsurf.com/v2 and include the program ID, for example /campaign/PROGRAM_ID. Authentication uses Bearer; account plan eligibility is required.",
    ),
    (
        "handwrytten",
        "official",
        "https://mcp.handwrytten.com/",
        "Dotobot uses mcp.handwrytten.com/mcp.",
    ),
    ("herobot", "none", "https://herobot.app/", "No developer API docs surfaced."),
    (
        "heyreach",
        "community",
        "https://github.com/bcharleson/heyreach-mcp",
        "Dotobot uses mcp.heyreach.io/mcp.",
    ),
    (
        "heysummit",
        "aggregator",
        "https://zapier.com/mcp/heysummit",
        "No dedicated server found.",
    ),
    (
        "hippo_video",
        "none",
        "https://help.hippovideo.io/",
        "No API/MCP docs surfaced.",
    ),
    (
        "hubspot",
        "official",
        "https://developers.hubspot.com/mcp",
        "Official public beta. Dotobot uses mcp.hubspot.com/anthropic.",
    ),
    (
        "humanitix",
        "official",
        "https://api.humanitix.com/v1/documentation/json",
        "Store the public API key from Humanitix Account > Advanced. Authentication uses x-api-key. Production paths are relative to /v1, for example GET /events with query page=1, or /tags. The current API reference also lists bodyless POST /events/EVENT_ID/tickets/TICKET_ID/check-in and check-out. Event creation, event updates and ticket transfers require additional provider permission. Old console API keys do not work. Staging and optional location override headers are not configured.",
    ),
    (
        "hygraph",
        "official",
        "https://hygraph.com/docs/hygraph-ai/mcp-server",
        "Dotobot uses mcp.hygraph.com/mcp.",
    ),
    (
        "hypeauditor",
        "aggregator",
        "https://composio.dev/toolkits/hypeauditor",
        "Also via Zapier.",
    ),
    (
        "hyperise",
        "aggregator",
        "https://composio.dev/toolkits/hyperise",
        "No dedicated vendor server.",
    ),
    ("icontact", "none", "https://www.icontact.com/", "No API/MCP docs surfaced."),
    (
        "impression",
        "none",
        "https://www.impressiondigital.com/",
        "No public API or MCP found.",
    ),
    (
        "indiefunnels",
        "none",
        "https://pipedream.com/apps/indiefunnels",
        "Generic Pipedream connector only.",
    ),
    (
        "infusionsoft",
        "official",
        "https://developer.infusionsoft.com/postman-quick-start/",
        "Infusionsoft is now Keap. Store a Personal Access Token or Service Account Key. Authentication uses X-Keap-API-Key. Paths are relative to /crm/rest/v1, for example GET /contacts; JSON bodies follow the REST v1 schema. This route does not use legacy XML-RPC keys or OAuth bearer tokens. REST v2 is not covered by this v1 base.",
    ),
    (
        "inksprout",
        "none",
        "https://inksprout.co/docs/index.html",
        "Only Zapier generic wrapper.",
    ),
    (
        "instabot",
        "none",
        "https://zapier.com/mcp/instabot",
        "Only Zapier generic wrapper.",
    ),
    (
        "instagram",
        "community",
        "https://github.com/AleemHaider/instagram-mcp",
        "Meta has no official server; Composio/Apify also offer wrappers.",
    ),
    (
        "instantly",
        "official",
        "https://help.instantly.ai/en/articles/12980002-instantly-mcp-model-context-protocol",
        "Dotobot uses mcp.instantly.ai/mcp.",
    ),
    (
        "instasent",
        "official",
        "https://docs.instasent.com/developers/product-api/authentication/",
        "Store a scoped Product API token. Paths are relative to https://api.instasent.com/v1, for example /project/PROJECT_UID. Include the real project UID in resource paths. Authentication uses Bearer. This route covers the Product API, not the separate transactional SMS API.",
    ),
    (
        "intercom",
        "official",
        "https://developers.intercom.com/docs/guides/mcp",
        "Official. Also github.com/intercom/intercom-mcp-server.",
    ),
    ("jellyreach", "none", "", "No clear public docs found."),
    (
        "jira",
        "official",
        "https://github.com/atlassian/atlassian-mcp-server",
        "Dotobot uses mcp.atlassian.com/v1/mcp (same server as Atlassian).",
    ),
    (
        "joggai",
        "official",
        "https://docs.jogg.ai/api-reference/v2/Webhook/ListWebhookEndpoints",
        "Store the JoggAI dashboard API key. Uses x-api-key with paths relative to /v2, for example GET /endpoints and POST /endpoint. Inspect the JSON code as well as HTTP status: only code 0 denotes success. JSON requests are supported; multipart uploads are not.",
    ),
    ("jvzoo", "none", "https://api.jvzoo.com/docs/", "No MCP found."),
    (
        "kartra",
        "none",
        "https://zapier.com/mcp/kartra",
        "Only Zapier/Pipedream generic wrappers.",
    ),
    (
        "kickofflabs",
        "none",
        "https://zapier.com/mcp/kickofflabs",
        "Only Zapier generic wrapper.",
    ),
    ("kingsumo", "none", "", "No public API docs site found."),
    (
        "klaviyo",
        "official",
        "https://developers.klaviyo.com/en/docs/klaviyo_mcp_server",
        "Dotobot uses mcp.klaviyo.com/mcp.",
    ),
    ("klenty", "none", "https://www.klenty.com/", "No dedicated MCP found."),
    (
        "kyvio",
        "none",
        "https://zapier.com/mcp/kyvio2",
        "Only Zapier generic wrapper.",
    ),
    (
        "lagrowthmachine",
        "community",
        "https://lobehub.com/mcp/gigradar-lgm-mcp-server",
        "Also via Composio; no official vendor server confirmed.",
    ),
    ("lahar", "none", "", "No vendor API docs surfaced."),
    (
        "laposta",
        "official",
        "https://api.laposta.nl/doc/index.en.php",
        "Store the Laposta API key alone; HTTP Basic uses it as the username with an empty password. Paths are relative to https://api.laposta.org/v2, for example GET /list. Regular writes use form fields with bracket notation for nested objects; POST /list/LIST_ID/members uses JSON for bulk synchronization. Pass the body as an object; Dotobot selects the encoding. Bulk synchronization requires a paid account.",
    ),
    (
        "lawmatics",
        "official",
        "https://help.lawmatics.com/en/articles/15939403-api-authentication-oauth2-setup-guide",
        "Store a Lawmatics OAuth access token obtained through a developer app. Authentication uses Bearer; paths are relative to /v1, for example GET /users/me. Lawmatics documents non-expiring tokens with no scopes and full account CRUD access; revoke through integration settings. This route does not perform OAuth consent. JSON bodies are supported, not multipart uploads.",
    ),
    (
        "lead_identity_check",
        "aggregator",
        "https://zapier.com/mcp/lead-identity-check",
        "Phone/address/email-to-name verification.",
    ),
    (
        "leaddyno",
        "none",
        "https://leaddyno.com/api_docs",
        "Only classic Zapier integration.",
    ),
    (
        "leadoku",
        "aggregator",
        "https://composio.dev/toolkits/leadoku/framework/claude-code",
        "Composio-hosted.",
    ),
    (
        "leadpops",
        "none",
        "https://zapier.com/apps/leadpops-leads/integrations",
        "Only classic Zapier integrations.",
    ),
    (
        "linear",
        "official",
        "https://linear.app/docs/mcp",
        "Linear-hosted remote MCP. Dotobot uses mcp.linear.app/mcp.",
    ),
    (
        "linkedin",
        "community",
        "https://github.com/stickerdaniel/linkedin-mcp-server",
        "No official LinkedIn MCP.",
    ),
    (
        "mailchimp",
        "none",
        "https://mailchimp.com/developer/marketing/api/",
        "No confirmed well-known MCP; use Marketing API.",
    ),
    (
        "microsoft_excel",
        "official",
        "https://learn.microsoft.com/en-us/graph/api/workbook-list-worksheets?view=graph-rest-1.0",
        "Store a current OAuth access token as the connector secret, not an API key, refresh token or client secret. Authentication uses Bearer. This route does not run OAuth consent or refresh expired tokens; replace the stored access token when it expires. GET /me/drive/items/ITEM_ID/workbook/worksheets lists worksheets. Use a delegated Graph token with Files.ReadWrite; application-only tokens are unsupported for this method. Calls are sessionless: workbook changes persist. Workbook-Session-Id and file uploads are not supported. Uses the global Graph cloud; paths omit /v1.0.",
    ),
    (
        "microsoft_outlook",
        "official",
        "https://learn.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0",
        "Store a current OAuth access token as the connector secret, not an API key, refresh token or client secret. Authentication uses Bearer. This route does not run OAuth consent or refresh expired tokens; replace the stored access token when it expires. GET /me/messages lists messages with delegated Mail.ReadBasic for basic properties; bodies need Mail.Read. Application tokens use /users/USER_ID/messages with application permissions. Mail writes need corresponding permissions. Uses the global Graph cloud; paths omit /v1.0.",
    ),
    (
        "microsoft_teams",
        "official",
        "https://learn.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-1.0",
        "Store a current OAuth access token as the connector secret, not an API key, refresh token or client secret. Authentication uses Bearer. This route does not run OAuth consent or refresh expired tokens; replace the stored access token when it expires. GET /me/joinedTeams requires delegated Team.ReadBasic.All with a work or school account. Personal accounts are unsupported. Application tokens use /users/USER_ID/joinedTeams. Other operations require their own permissions. Uses the global Graph cloud; paths omit /v1.0.",
    ),
    (
        "monday",
        "official",
        "https://developer.monday.com/apps/docs/mondaycom-mcp-integration",
        "Official. Open-source impl: github.com/mondaycom/monday-ai.",
    ),
    (
        "notion",
        "official",
        "https://developers.notion.com/docs/mcp",
        "Notion-hosted remote MCP via OAuth. Dotobot uses mcp.notion.com/mcp.",
    ),
    (
        "openai",
        "none",
        "https://platform.openai.com/docs/api-reference",
        "Primarily an MCP client/host, not a server. This is a provider, not a service MCP.",
    ),
    (
        "pipedrive",
        "aggregator",
        "https://composio.dev/toolkits/pipedrive",
        "Dotobot uses mcp.pipedrive.com/mcp.",
    ),
    (
        "quickbooks",
        "aggregator",
        "https://composio.dev/toolkits/quickbooks",
        "105 tools; no official Intuit-published MCP.",
    ),
    (
        "salesforce",
        "official",
        "https://github.com/salesforcecli/mcp",
        "Salesforce DX MCP Server (npm: @salesforce/mcp).",
    ),
    (
        "shopify",
        "official",
        "https://shopify.dev/docs/apps/build/storefront-mcp",
        "Storefront + Customer Accounts MCP. Dotobot uses https://{store_domain}/api/mcp.",
    ),
    (
        "slack",
        "community",
        "https://github.com/korotovsky/slack-mcp-server",
        "Table lists a community server; harness already uses official mcp.slack.com/mcp.",
    ),
    (
        "stripe",
        "official",
        "https://docs.stripe.com/mcp",
        "Official. Hosted at mcp.stripe.com.",
    ),
    (
        "telegram",
        "community",
        "https://github.com/sparfenyuk/mcp-telegram",
        "No official Telegram MCP.",
    ),
    (
        "trello",
        "official",
        "https://github.com/atlassian/trello-mcp-server",
        "Dotobot uses mcp.trello.com/v1.",
    ),
    (
        "twilio",
        "official",
        "https://github.com/twilio-labs/mcp",
        "Official. Docs: twilio.com/docs/ai/mcp.",
    ),
    (
        "typeform",
        "official",
        "https://www.typeform.com/developers/mcp/",
        "Dotobot uses api.typeform.com/mcp.",
    ),
    (
        "whatsapp",
        "none",
        "https://developers.facebook.com/docs/whatsapp/",
        "No official Meta MCP; unofficial community servers exist.",
    ),
    (
        "woocommerce",
        "official",
        "https://developer.woocommerce.com/docs/features/mcp/",
        "Official beta as of late 2025.",
    ),
    (
        "xero",
        "official",
        "https://github.com/XeroAPI/xero-mcp-server",
        "Dotobot uses mcp.xero.com/mcp.",
    ),
    (
        "zendesk",
        "none",
        "https://developer.zendesk.com/api-reference/",
        "No official vendor MCP; community + Zapier only.",
    ),
    (
        "zoom",
        "official",
        "https://developers.zoom.us/docs/mcp/",
        "Official. Dotobot uses mcp.zoom.us/mcp/meeting/streamable.",
    ),
    # Live catalog types that were not in the HeyMarcus table.
    (
        "ahrefs",
        "official",
        "https://docs.ahrefs.com/mcp/docs/introduction",
        "Official hosted MCP at api.ahrefs.com/mcp/mcp. Streamable HTTP + OAuth. Lite plan or higher.",
    ),
    (
        "granola",
        "official",
        "https://docs.granola.ai/help-center/sharing/integrations/mcp",
        "Official hosted MCP at mcp.granola.ai/mcp.",
    ),
    (
        "n8n",
        "official",
        "https://docs.n8n.io/advanced-ai/mcp/accessing-n8n-mcp-server/",
        "Instance MCP at https://{host}/mcp-server/http. OAuth or bearer token. Enable in Settings → Instance-level MCP.",
    ),
    (
        "triggerdev",
        "none",
        "https://trigger.dev/docs/mcp-introduction",
        "Official MCP is CLI stdio only (npx trigger.dev@latest mcp). No hosted HTTP URL.",
    ),
    (
        "1password",
        "none",
        "https://www.1password.dev/environments/mcp-server",
        "Official MCP is local stdio only (1password-mcp via the desktop app). No hosted HTTP URL. www.1password.dev/mcp is Mintlify docs search, not vaults.",
    ),
    (
        "google",
        "none",
        "https://developers.google.com/workspace",
        "Umbrella Google stub. Prefer the Gmail / Calendar / Drive / Sheets / Ads entries.",
    ),
    (
        "cloudflare",
        "official",
        "https://developers.cloudflare.com/agents/model-context-protocol/cloudflare/servers-for-cloudflare/",
        "Dotobot uses mcp.cloudflare.com/mcp (OAuth, or a pasted API token as bearer).",
    ),
    (
        "paypal",
        "official",
        "https://developer.paypal.com/",
        "Dotobot uses mcp.paypal.com/mcp.",
    ),
    (
        "square",
        "official",
        "https://developer.squareup.com/",
        "Dotobot uses mcp.squareup.com/mcp.",
    ),
    (
        "sentry",
        "official",
        "https://docs.sentry.io/",
        "Dotobot uses mcp.sentry.dev/mcp.",
    ),
    (
        "vercel",
        "official",
        "https://vercel.com/docs",
        "Dotobot uses mcp.vercel.com.",
    ),
    (
        "posthog",
        "official",
        "https://posthog.com/docs",
        "Dotobot uses mcp.posthog.com/mcp.",
    ),
    (
        "amplitude",
        "official",
        "https://amplitude.com/docs",
        "Dotobot uses mcp.amplitude.com/mcp.",
    ),
    (
        "miro",
        "official",
        "https://developers.miro.com/",
        "Dotobot uses mcp.miro.com/.",
    ),
    (
        "canva",
        "official",
        "https://www.canva.dev/docs/connect/",
        "Dotobot uses mcp.canva.com/mcp.",
    ),
    (
        "webflow",
        "official",
        "https://developers.webflow.com/mcp/reference/overview",
        "Dotobot uses mcp.webflow.com/mcp.",
    ),
    (
        "zapier",
        "official",
        "https://zapier.com/mcp",
        "Dotobot uses mcp.zapier.com/api/v1/connect.",
    ),
    (
        "composio",
        "official",
        "https://docs.composio.dev/docs/composio-connect",
        "Official hosted MCP at connect.composio.dev/mcp. Streamable HTTP + OAuth. Seven meta-tools over 1000+ apps.",
    ),
    (
        "atlassian",
        "official",
        "https://github.com/atlassian/atlassian-mcp-server",
        "Rovo MCP. Dotobot uses mcp.atlassian.com/v1/mcp. Jira is also a separate gallery stub.",
    ),
]

DOCS: dict[str, dict[str, str]] = {}
for _type, _publisher, _docs, _notes in _ROWS:
    if _type in DOCS:
        raise ValueError(f"duplicate connector_docs type {_type}")
    DOCS[_type] = {"publisher": _publisher, "docs": _docs, "notes": _notes}
